//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ED.AdminPanel.Blazor.Pages.Templates {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AddPermissionsModalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AddPermissionsModalResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ED.AdminPanel.Blazor.Pages.Templates.AddPermissionsModalResources", typeof(AddPermissionsModalResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добави.
        /// </summary>
        public static string AddBtn {
            get {
                return ResourceManager.GetString("AddBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Откажи.
        /// </summary>
        public static string CancelBtn {
            get {
                return ResourceManager.GetString("CancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получаване.
        /// </summary>
        public static string CanReceive {
            get {
                return ResourceManager.GetString("CanReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изпращане.
        /// </summary>
        public static string CanSend {
            get {
                return ResourceManager.GetString("CanSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профили.
        /// </summary>
        public static string ProfileIds {
            get {
                return ResourceManager.GetString("ProfileIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поне едно от полетата Изпращане или Получаване трябва да е попълнено.
        /// </summary>
        public static string RequireCanSendOrCanReceiveErrorMessage {
            get {
                return ResourceManager.GetString("RequireCanSendOrCanReceiveErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поне едно от полетата Профили или Групи трябва да бъде попълнено.
        /// </summary>
        public static string RequireProfileOrTargetGroupErrorMessage {
            get {
                return ResourceManager.GetString("RequireProfileOrTargetGroupErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Групи.
        /// </summary>
        public static string TargetGroupIds {
            get {
                return ResourceManager.GetString("TargetGroupIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Достъп до шаблона.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
