//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ED.Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Notifications {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Notifications() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ED.Domain.Resources.Notifications", typeof(Notifications).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здравейте {0},
        ///
        ///Изпратено през профил {1} съобщение &quot;{2}&quot; е отворено от {3}. Можете да проверите детайли за отварянето, като  влезете в профила си на адрес {4}
        ///
        ///Това съобщение e изпратено от Система за сигурно електронно връчване, която се изгражда и поддържа от Министерство на електронното управление по силата на чл. 26 от Закона за електронно управление. Информацията в съобщението е предназначена само за получателя/ите. Всяко неоторизирано използване или разпространяване на това съобщение или на части [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DeliveredEmailBody {
            get {
                return ResourceManager.GetString("DeliveredEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Министерство на електронното управление, Система  за сигурно електронно връчване – Отворено съобщение!.
        /// </summary>
        public static string DeliveredEmailSubject {
            get {
                return ResourceManager.GetString("DeliveredEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} : Washeto syobstenie be otvoreno ot {1}.
        /// </summary>
        public static string DeliveredSMSBody {
            get {
                return ResourceManager.GetString("DeliveredSMSBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} : Вашето съобщение бе отворено от {1}.
        /// </summary>
        public static string DeliveredViberBody {
            get {
                return ResourceManager.GetString("DeliveredViberBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здравейте {0},
        ///
        ///Току-що на {0} бе връчено ново съобщение/документи от {1}. 
        ///Можете да го получите като влезете на адрес {2} и въведете код за достъп: {3}
        ///
        ///Това съобщение e изпратено от Система за сигурно електронно връчване, която се изгражда и поддържа от Министерство на електронното управление по силата на чл. 26 от Закона за електронно управление. Информацията в съобщението е предназначена само за получателя/ите притежаващи код за достъп до съобщението. Всяко неоторизирано достъпване или разпростран [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ReceivedCodeMessageEmailBody {
            get {
                return ResourceManager.GetString("ReceivedCodeMessageEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Министерство на електронното управление, Система  за сигурно електронно връчване – съобщение с код за достъп!.
        /// </summary>
        public static string ReceivedCodeMessageEmailSubject {
            get {
                return ResourceManager.GetString("ReceivedCodeMessageEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///KOD ZA DOSTAP:{1}
        ///Imate saobshtenie ot {2}..
        /// </summary>
        public static string ReceivedCodeMessageSMSBody {
            get {
                return ResourceManager.GetString("ReceivedCodeMessageSMSBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здравейте {0},
        ///
        ///Току що на профил {1} бе връчено ново съобщение/документи от {2}. Можете да го получите като  като влезете в профила си на адрес {3}
        ///
        ///Това съобщение e изпратено от Система за сигурно електронно връчване, която се изгражда и поддържа от Министерство на електронното управление по силата на чл. 26 от Закона за електронно управление. Информацията в съобщението е предназначена само за получателя/ите. Всяко неоторизирано използване или разпространяване на това съобщение или на части от него е  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ReceivedEmailBody {
            get {
                return ResourceManager.GetString("ReceivedEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Министерство на електронното управление, Система  за сигурно електронно връчване – Ново получено съобщение!.
        /// </summary>
        public static string ReceivedEmailSubject {
            get {
                return ResourceManager.GetString("ReceivedEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} : Ima novo vrycheno syobstenie za  {1} ot {2}..
        /// </summary>
        public static string ReceivedSMSBody {
            get {
                return ResourceManager.GetString("ReceivedSMSBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} : Има ново връчено съобщение за {1} от {2}..
        /// </summary>
        public static string ReceivedViberBody {
            get {
                return ResourceManager.GetString("ReceivedViberBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здравейте,
        ///
        ///Профил {0} е успешно регистриран в системата за сигурно електронно връчване. Можете да започнете да използвате профила си като се логнете в системата на адрес {1} 
        ///
        ///
        ///Това съобщение e изпратено от Система за сигурно електронно връчване, която се изгражда и поддържа от Министерство на електронното управление по силата на чл. 26 от Закона за електронно управление. Информацията в съобщението е предназначена само за получателя/ите. Всяко неоторизирано използване или разпространяване на това съоб [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RegistrationProfileEmailBody {
            get {
                return ResourceManager.GetString("RegistrationProfileEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Министерство на електронното управление, Система  за сигурно електронно връчване - Профил {0} е акивиран!.
        /// </summary>
        public static string RegistrationProfileEmailSubject {
            get {
                return ResourceManager.GetString("RegistrationProfileEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здравейте {0},
        ///
        ///Регистрираният от вас профил {1} в системата за сигурно електронно връчване беше успешно активиран. Можете да започнете да използвате профила си като се логнете в системата на адрес {2} 
        ///
        ///
        ///Това съобщение e изпратено от Система за сигурно електронно връчване, която се изгражда и поддържа от Министерство на електронното управление по силата на чл. 26 от Закона за електронно управление. Информацията в съобщението е предназначена само за получателя/ите. Всяко неоторизирано използване или ра [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RegistrationRequestConfirmedEmailBody {
            get {
                return ResourceManager.GetString("RegistrationRequestConfirmedEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Министерство на електронното управление, Система  за сигурно електронно връчване - Профил {0} е акивиран!.
        /// </summary>
        public static string RegistrationRequestConfirmedEmailSubject {
            get {
                return ResourceManager.GetString("RegistrationRequestConfirmedEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здравейте {0},
        ///
        ///Регистрираният от Вас профил {1} в системата за сигурно електронно връчване е закрит от администратор на системата.  За повече информация, моля свържете се с администрацията на Системата за сигурно електронно връчване.
        ///
        ///
        ///Това съобщение e изпратено от Система за сигурно електронно връчване, която се изгражда и поддържа от Министерство на електронното управление по силата на чл. 26 от Закона за електронно управление. Информацията в съобщението е предназначена само за получателя/ите. Всяко [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RegistrationRequestRejectedEmailBody {
            get {
                return ResourceManager.GetString("RegistrationRequestRejectedEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Министерство на електронното управление, Система за сигурно електронно връчване - Профил {0} е закрит!.
        /// </summary>
        public static string RegistrationRequestRejectedEmailSubject {
            get {
                return ResourceManager.GetString("RegistrationRequestRejectedEmailSubject", resourceCulture);
            }
        }
    }
}
