//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDelivery.SEOS.EGovEndpoint {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.egov.bg/messaging/", ConfigurationName="EGovEndpoint.IEGovService")]
    public interface IEGovService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.egov.bg/messaging/IEGovService/Submit", ReplyAction="http://services.egov.bg/messaging/IEGovService/SubmitResponse")]
        string Submit(string request);
        
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEGovServiceChannel : EDelivery.SEOS.EGovEndpoint.IEGovService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EGovServiceClient : System.ServiceModel.ClientBase<EDelivery.SEOS.EGovEndpoint.IEGovService>, EDelivery.SEOS.EGovEndpoint.IEGovService {
        
        public EGovServiceClient() {
        }
        
        public EGovServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EGovServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EGovServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EGovServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Submit(string request) {
            return base.Channel.Submit(request);
        }
        
    }
}
