//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ED.AdminPanel.Blazor.Pages.Profiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AddIntegrationLoginModalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AddIntegrationLoginModalResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ED.AdminPanel.Blazor.Pages.Profiles.AddIntegrationLoginModalResources", typeof(AddIntegrationLoginModalResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Откажи.
        /// </summary>
        public static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запази.
        /// </summary>
        public static string BtnSubmit {
            get {
                return ResourceManager.GetString("BtnSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имейл.
        /// </summary>
        public static string FieldEmail {
            get {
                return ResourceManager.GetString("FieldEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЕИК.
        /// </summary>
        public static string FieldIdentifier {
            get {
                return ResourceManager.GetString("FieldIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име.
        /// </summary>
        public static string FieldName {
            get {
                return ResourceManager.GetString("FieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефонен номер.
        /// </summary>
        public static string FieldPhone {
            get {
                return ResourceManager.GetString("FieldPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Целева група.
        /// </summary>
        public static string FieldTargetGroup {
            get {
                return ResourceManager.GetString("FieldTargetGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Право за изпращане от името на чужд профил.
        /// </summary>
        public static string FormCanSendOnBehalfOf {
            get {
                return ResourceManager.GetString("FormCanSendOnBehalfOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цифров отпечатък на сертификат.
        /// </summary>
        public static string FormCertificateThumbPrint {
            get {
                return ResourceManager.GetString("FormCertificateThumbPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email адрес.
        /// </summary>
        public static string FormEmail {
            get {
                return ResourceManager.GetString("FormEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нотификации по e-mail при получаване на ново съобщение.
        /// </summary>
        public static string FormEmailNotificationActive {
            get {
                return ResourceManager.GetString("FormEmailNotificationActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нотификации по e-mail при отваряне на съобщение.
        /// </summary>
        public static string FormEmailNotificationOnDeliveryActive {
            get {
                return ResourceManager.GetString("FormEmailNotificationOnDeliveryActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        public static string FormPhone {
            get {
                return ResourceManager.GetString("FormPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL за нотификации.
        /// </summary>
        public static string FormPushNotificationsUrl {
            get {
                return ResourceManager.GetString("FormPushNotificationsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нотификации по SMS при получаване на ново съобщение.
        /// </summary>
        public static string FormSmsNotificationActive {
            get {
                return ResourceManager.GetString("FormSmsNotificationActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нотификации по SMS при отваряне на съобщение.
        /// </summary>
        public static string FormSmsNotificationOnDeliveryActive {
            get {
                return ResourceManager.GetString("FormSmsNotificationOnDeliveryActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нотификации по Viber при получаване на ново съобщение.
        /// </summary>
        public static string FormViberNotificationActive {
            get {
                return ResourceManager.GetString("FormViberNotificationActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нотификации по Viber при отваряне на съобщение.
        /// </summary>
        public static string FormViberNotificationOnDeliveryActive {
            get {
                return ResourceManager.GetString("FormViberNotificationOnDeliveryActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редакция на интеграцинен логин.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
