//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ED.AdminPanel.Blazor.Pages.Profiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AddLoginModalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AddLoginModalResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ED.AdminPanel.Blazor.Pages.Profiles.AddLoginModalResources", typeof(AddLoginModalResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добави.
        /// </summary>
        public static string BtnAdd {
            get {
                return ResourceManager.GetString("BtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Откажи.
        /// </summary>
        public static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продължи.
        /// </summary>
        public static string BtnContinue {
            get {
                return ResourceManager.GetString("BtnContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Четене.
        /// </summary>
        public static string ColumnHasReadPermission {
            get {
                return ResourceManager.GetString("ColumnHasReadPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Писане.
        /// </summary>
        public static string ColumnHasWritePermission {
            get {
                return ResourceManager.GetString("ColumnHasWritePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шаблон.
        /// </summary>
        public static string ColumnTemplateName {
            get {
                return ResourceManager.GetString("ColumnTemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЕГН / Идентификатор на чужденец.
        /// </summary>
        public static string FieldIdentifier {
            get {
                return ResourceManager.GetString("FieldIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Роля администратор.
        /// </summary>
        public static string FieldIsAdmin {
            get {
                return ResourceManager.GetString("FieldIsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Роля представител с пълни права.
        /// </summary>
        public static string FieldIsFullAccessMember {
            get {
                return ResourceManager.GetString("FieldIsFullAccessMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Роля представител.
        /// </summary>
        public static string FieldIsRepresentative {
            get {
                return ResourceManager.GetString("FieldIsRepresentative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребител.
        /// </summary>
        public static string FieldProfileElectronicSubjectName {
            get {
                return ResourceManager.GetString("FieldProfileElectronicSubjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не беше намерен активен потребител с въведения идентификатор.
        /// </summary>
        public static string PersonNotFoundError {
            get {
                return ResourceManager.GetString("PersonNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въведи идентификатор.
        /// </summary>
        public static string TitleFindIndividual {
            get {
                return ResourceManager.GetString("TitleFindIndividual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въведи права.
        /// </summary>
        public static string TitleSetPermissions {
            get {
                return ResourceManager.GetString("TitleSetPermissions", resourceCulture);
            }
        }
    }
}
