//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ED.AdminPanel.Blazor.Pages.Requests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EditResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EditResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ED.AdminPanel.Blazor.Pages.Requests.EditResources", typeof(EditResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Одобряване.
        /// </summary>
        public static string BtnConfirm {
            get {
                return ResourceManager.GetString("BtnConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отхвърляне.
        /// </summary>
        public static string BtnReject {
            get {
                return ResourceManager.GetString("BtnReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основание.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата на създаване.
        /// </summary>
        public static string CreateDate {
            get {
                return ResourceManager.GetString("CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Създадено от.
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email за контакт.
        /// </summary>
        public static string CreatedEmail {
            get {
                return ResourceManager.GetString("CreatedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Относно регистрация на.
        /// </summary>
        public static string CreatedFor {
            get {
                return ResourceManager.GetString("CreatedFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон за контакт.
        /// </summary>
        public static string CreatedPhone {
            get {
                return ResourceManager.GetString("CreatedPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        public static string FieldProcessDate {
            get {
                return ResourceManager.GetString("FieldProcessDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автор.
        /// </summary>
        public static string FieldProcessUser {
            get {
                return ResourceManager.GetString("FieldProcessUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основание.
        /// </summary>
        public static string FieldReason {
            get {
                return ResourceManager.GetString("FieldReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основание.
        /// </summary>
        public static string FormReason {
            get {
                return ResourceManager.GetString("FormReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистриран от.
        /// </summary>
        public static string ProfileAuthor {
            get {
                return ResourceManager.GetString("ProfileAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email адрес.
        /// </summary>
        public static string ProfileEmail {
            get {
                return ResourceManager.GetString("ProfileEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЕИК.
        /// </summary>
        public static string ProfileIdentifier {
            get {
                return ResourceManager.GetString("ProfileIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име.
        /// </summary>
        public static string ProfileName {
            get {
                return ResourceManager.GetString("ProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        public static string ProfilePhone {
            get {
                return ResourceManager.GetString("ProfilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зявление за регистрация.
        /// </summary>
        public static string ProfileRegistrationRequest {
            get {
                return ResourceManager.GetString("ProfileRegistrationRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изтегли.
        /// </summary>
        public static string ProfileRegistrationRequestDownload {
            get {
                return ResourceManager.GetString("ProfileRegistrationRequestDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес.
        /// </summary>
        public static string ProfileResidence {
            get {
                return ResourceManager.GetString("ProfileResidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заверен от.
        /// </summary>
        public static string SignatureCertifiedBy {
            get {
                return ResourceManager.GetString("SignatureCertifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подписан от.
        /// </summary>
        public static string SignatureSignedBy {
            get {
                return ResourceManager.GetString("SignatureSignedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Валиден от.
        /// </summary>
        public static string SignatureValidFrom {
            get {
                return ResourceManager.GetString("SignatureValidFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Валидност на сертификата.
        /// </summary>
        public static string SignatureValidity {
            get {
                return ResourceManager.GetString("SignatureValidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невалиден.
        /// </summary>
        public static string SignatureValidityStatus_False {
            get {
                return ResourceManager.GetString("SignatureValidityStatus_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Валиден.
        /// </summary>
        public static string SignatureValidityStatus_True {
            get {
                return ResourceManager.GetString("SignatureValidityStatus_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Валиден до.
        /// </summary>
        public static string SignatureValidTo {
            get {
                return ResourceManager.GetString("SignatureValidTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Одобрен.
        /// </summary>
        public static string Status_Confirmed {
            get {
                return ResourceManager.GetString("Status_Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изтрит.
        /// </summary>
        public static string Status_Deleted {
            get {
                return ResourceManager.GetString("Status_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нов.
        /// </summary>
        public static string Status_New {
            get {
                return ResourceManager.GetString("Status_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отказан.
        /// </summary>
        public static string Status_Rejected {
            get {
                return ResourceManager.GetString("Status_Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Преглед на заявление за регистрация.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Одобрение / Отказ.
        /// </summary>
        public static string TitleActionsSection {
            get {
                return ResourceManager.GetString("TitleActionsSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данни от заявлението.
        /// </summary>
        public static string TitleDataSection {
            get {
                return ResourceManager.GetString("TitleDataSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данни от КЕП.
        /// </summary>
        public static string TItleSignaturesSection {
            get {
                return ResourceManager.GetString("TItleSignaturesSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус на заявлението.
        /// </summary>
        public static string TitleStatusSection {
            get {
                return ResourceManager.GetString("TitleStatusSection", resourceCulture);
            }
        }
    }
}
