//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDelivery.SEOS.EDeliveryAS4Node {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://eu.domibus.wsplugin/")]
    public partial class FaultDetail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eu.domibus.wsplugin/")]
    public partial class errorResultImpl : object, System.ComponentModel.INotifyPropertyChanged {
        
        private domibusErrorCode domibusErrorCodeField;
        
        private bool domibusErrorCodeFieldSpecified;
        
        private string errorDetailField;
        
        private string messageInErrorIdField;
        
        private mshRole mshRoleField;
        
        private bool mshRoleFieldSpecified;
        
        private System.DateTime notifiedField;
        
        private bool notifiedFieldSpecified;
        
        private System.DateTime timestampField;
        
        private bool timestampFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public domibusErrorCode domibusErrorCode {
            get {
                return this.domibusErrorCodeField;
            }
            set {
                this.domibusErrorCodeField = value;
                this.RaisePropertyChanged("domibusErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool domibusErrorCodeSpecified {
            get {
                return this.domibusErrorCodeFieldSpecified;
            }
            set {
                this.domibusErrorCodeFieldSpecified = value;
                this.RaisePropertyChanged("domibusErrorCodeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string errorDetail {
            get {
                return this.errorDetailField;
            }
            set {
                this.errorDetailField = value;
                this.RaisePropertyChanged("errorDetail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string messageInErrorId {
            get {
                return this.messageInErrorIdField;
            }
            set {
                this.messageInErrorIdField = value;
                this.RaisePropertyChanged("messageInErrorId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public mshRole mshRole {
            get {
                return this.mshRoleField;
            }
            set {
                this.mshRoleField = value;
                this.RaisePropertyChanged("mshRole");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mshRoleSpecified {
            get {
                return this.mshRoleFieldSpecified;
            }
            set {
                this.mshRoleFieldSpecified = value;
                this.RaisePropertyChanged("mshRoleSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime notified {
            get {
                return this.notifiedField;
            }
            set {
                this.notifiedField = value;
                this.RaisePropertyChanged("notified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool notifiedSpecified {
            get {
                return this.notifiedFieldSpecified;
            }
            set {
                this.notifiedFieldSpecified = value;
                this.RaisePropertyChanged("notifiedSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
                this.RaisePropertyChanged("timestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timestampSpecified {
            get {
                return this.timestampFieldSpecified;
            }
            set {
                this.timestampFieldSpecified = value;
                this.RaisePropertyChanged("timestampSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eu.domibus.wsplugin/")]
    public enum domibusErrorCode {
        
        /// <remarks/>
        EBMS_0001,
        
        /// <remarks/>
        EBMS_0002,
        
        /// <remarks/>
        EBMS_0003,
        
        /// <remarks/>
        EBMS_0004,
        
        /// <remarks/>
        EBMS_0005,
        
        /// <remarks/>
        EBMS_0006,
        
        /// <remarks/>
        EBMS_0007,
        
        /// <remarks/>
        EBMS_0008,
        
        /// <remarks/>
        EBMS_0009,
        
        /// <remarks/>
        EBMS_0010,
        
        /// <remarks/>
        EBMS_0011,
        
        /// <remarks/>
        EBMS_0101,
        
        /// <remarks/>
        EBMS_0102,
        
        /// <remarks/>
        EBMS_0103,
        
        /// <remarks/>
        EBMS_0201,
        
        /// <remarks/>
        EBMS_0202,
        
        /// <remarks/>
        EBMS_0301,
        
        /// <remarks/>
        EBMS_0302,
        
        /// <remarks/>
        EBMS_0303,
        
        /// <remarks/>
        EBMS_0020,
        
        /// <remarks/>
        EBMS_0021,
        
        /// <remarks/>
        EBMS_0022,
        
        /// <remarks/>
        EBMS_0023,
        
        /// <remarks/>
        EBMS_0030,
        
        /// <remarks/>
        EBMS_0031,
        
        /// <remarks/>
        EBMS_0040,
        
        /// <remarks/>
        EBMS_0041,
        
        /// <remarks/>
        EBMS_0042,
        
        /// <remarks/>
        EBMS_0043,
        
        /// <remarks/>
        EBMS_0044,
        
        /// <remarks/>
        EBMS_0045,
        
        /// <remarks/>
        EBMS_0046,
        
        /// <remarks/>
        EBMS_0047,
        
        /// <remarks/>
        EBMS_0048,
        
        /// <remarks/>
        EBMS_0049,
        
        /// <remarks/>
        EBMS_0050,
        
        /// <remarks/>
        EBMS_0051,
        
        /// <remarks/>
        EBMS_0052,
        
        /// <remarks/>
        EBMS_0053,
        
        /// <remarks/>
        EBMS_0054,
        
        /// <remarks/>
        EBMS_0055,
        
        /// <remarks/>
        EBMS_0060,
        
        /// <remarks/>
        EBMS_0065,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eu.domibus.wsplugin/")]
    public enum mshRole {
        
        /// <remarks/>
        SENDING,
        
        /// <remarks/>
        RECEIVING,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://eu.domibus.wsplugin/", ConfigurationName="EDeliveryAS4Node.WebServicePluginInterface")]
    public interface WebServicePluginInterface {
        
        // CODEGEN: Generating message contract since the operation getMessageErrors is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EDelivery.SEOS.EDeliveryAS4Node.FaultDetail), Action="", Name="FaultDetail")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        EDelivery.SEOS.EDeliveryAS4Node.getMessageErrorsResponse getMessageErrors(EDelivery.SEOS.EDeliveryAS4Node.getMessageErrors request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EDelivery.SEOS.EDeliveryAS4Node.getMessageErrorsResponse> getMessageErrorsAsync(EDelivery.SEOS.EDeliveryAS4Node.getMessageErrors request);
        
        // CODEGEN: Generating message contract since the operation getStatus is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EDelivery.SEOS.EDeliveryAS4Node.FaultDetail), Action="", Name="FaultDetail")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        EDelivery.SEOS.EDeliveryAS4Node.getStatusResponse getStatus(EDelivery.SEOS.EDeliveryAS4Node.getStatus request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EDelivery.SEOS.EDeliveryAS4Node.getStatusResponse> getStatusAsync(EDelivery.SEOS.EDeliveryAS4Node.getStatus request);
        
        // CODEGEN: Generating message contract since the operation submitMessage is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EDelivery.SEOS.EDeliveryAS4Node.FaultDetail), Action="", Name="FaultDetail")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        EDelivery.SEOS.EDeliveryAS4Node.submitMessageResponse submitMessage(EDelivery.SEOS.EDeliveryAS4Node.submitMessage request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EDelivery.SEOS.EDeliveryAS4Node.submitMessageResponse> submitMessageAsync(EDelivery.SEOS.EDeliveryAS4Node.submitMessage request);
        
        // CODEGEN: Generating message contract since the operation retrieveMessage is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EDelivery.SEOS.EDeliveryAS4Node.FaultDetail), Action="", Name="FaultDetail")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        EDelivery.SEOS.EDeliveryAS4Node.retrieveMessageResponse1 retrieveMessage(EDelivery.SEOS.EDeliveryAS4Node.retrieveMessage request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EDelivery.SEOS.EDeliveryAS4Node.retrieveMessageResponse1> retrieveMessageAsync(EDelivery.SEOS.EDeliveryAS4Node.retrieveMessage request);
        
        // CODEGEN: Generating message contract since the operation listPendingMessages is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EDelivery.SEOS.EDeliveryAS4Node.FaultDetail), Action="", Name="FaultDetail")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        EDelivery.SEOS.EDeliveryAS4Node.listPendingMessagesResponse listPendingMessages(EDelivery.SEOS.EDeliveryAS4Node.listPendingMessages request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EDelivery.SEOS.EDeliveryAS4Node.listPendingMessagesResponse> listPendingMessagesAsync(EDelivery.SEOS.EDeliveryAS4Node.listPendingMessages request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://eu.domibus.wsplugin/")]
    public partial class getErrorsRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string messageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
                this.RaisePropertyChanged("messageID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMessageErrors {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://eu.domibus.wsplugin/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public EDelivery.SEOS.EDeliveryAS4Node.getErrorsRequest getErrorsRequest;
        
        public getMessageErrors() {
        }
        
        public getMessageErrors(EDelivery.SEOS.EDeliveryAS4Node.getErrorsRequest getErrorsRequest) {
            this.getErrorsRequest = getErrorsRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMessageErrorsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getMessageErrorsResponse", Namespace="http://eu.domibus.wsplugin/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EDelivery.SEOS.EDeliveryAS4Node.errorResultImpl[] getMessageErrorsResponse1;
        
        public getMessageErrorsResponse() {
        }
        
        public getMessageErrorsResponse(EDelivery.SEOS.EDeliveryAS4Node.errorResultImpl[] getMessageErrorsResponse1) {
            this.getMessageErrorsResponse1 = getMessageErrorsResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://eu.domibus.wsplugin/")]
    public partial class statusRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string messageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
                this.RaisePropertyChanged("messageID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eu.domibus.wsplugin/")]
    public enum messageStatus {
        
        /// <remarks/>
        READY_TO_SEND,
        
        /// <remarks/>
        READY_TO_PULL,
        
        /// <remarks/>
        BEING_PULLED,
        
        /// <remarks/>
        SEND_ENQUEUED,
        
        /// <remarks/>
        SEND_IN_PROGRESS,
        
        /// <remarks/>
        WAITING_FOR_RECEIPT,
        
        /// <remarks/>
        ACKNOWLEDGED,
        
        /// <remarks/>
        ACKNOWLEDGED_WITH_WARNING,
        
        /// <remarks/>
        SEND_ATTEMPT_FAILED,
        
        /// <remarks/>
        SEND_FAILURE,
        
        /// <remarks/>
        NOT_FOUND,
        
        /// <remarks/>
        WAITING_FOR_RETRY,
        
        /// <remarks/>
        RECEIVED,
        
        /// <remarks/>
        RECEIVED_WITH_WARNINGS,
        
        /// <remarks/>
        DELETED,
        
        /// <remarks/>
        DOWNLOADED,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getStatus {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://eu.domibus.wsplugin/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public EDelivery.SEOS.EDeliveryAS4Node.statusRequest statusRequest;
        
        public getStatus() {
        }
        
        public getStatus(EDelivery.SEOS.EDeliveryAS4Node.statusRequest statusRequest) {
            this.statusRequest = statusRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getStatusResponse", Namespace="http://eu.domibus.wsplugin/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<messageStatus> getStatusResponse1;
        
        public getStatusResponse() {
        }
        
        public getStatusResponse(System.Nullable<messageStatus> getStatusResponse1) {
            this.getStatusResponse1 = getStatusResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/")]
    public partial class Messaging : object, System.ComponentModel.INotifyPropertyChanged {
        
        private UserMessage userMessageField;
        
        private bool mustUnderstandField;
        
        private bool mustUnderstandFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public UserMessage UserMessage {
            get {
                return this.userMessageField;
            }
            set {
                this.userMessageField = value;
                this.RaisePropertyChanged("UserMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool mustUnderstand {
            get {
                return this.mustUnderstandField;
            }
            set {
                this.mustUnderstandField = value;
                this.RaisePropertyChanged("mustUnderstand");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mustUnderstandSpecified {
            get {
                return this.mustUnderstandFieldSpecified;
            }
            set {
                this.mustUnderstandFieldSpecified = value;
                this.RaisePropertyChanged("mustUnderstandSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/")]
    public partial class UserMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MessageInfo messageInfoField;
        
        private PartyInfo partyInfoField;
        
        private CollaborationInfo collaborationInfoField;
        
        private Property[] messagePropertiesField;
        
        private PartInfo[] payloadInfoField;
        
        private ProcessingType processingTypeField;
        
        private string mpcField;
        
        public UserMessage() {
            this.processingTypeField = ProcessingType.PUSH;
        }
        
        /// <remarks/>
        public MessageInfo MessageInfo {
            get {
                return this.messageInfoField;
            }
            set {
                this.messageInfoField = value;
                this.RaisePropertyChanged("MessageInfo");
            }
        }
        
        /// <remarks/>
        public PartyInfo PartyInfo {
            get {
                return this.partyInfoField;
            }
            set {
                this.partyInfoField = value;
                this.RaisePropertyChanged("PartyInfo");
            }
        }
        
        /// <remarks/>
        public CollaborationInfo CollaborationInfo {
            get {
                return this.collaborationInfoField;
            }
            set {
                this.collaborationInfoField = value;
                this.RaisePropertyChanged("CollaborationInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Property[] MessageProperties {
            get {
                return this.messagePropertiesField;
            }
            set {
                this.messagePropertiesField = value;
                this.RaisePropertyChanged("MessageProperties");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public PartInfo[] PayloadInfo {
            get {
                return this.payloadInfoField;
            }
            set {
                this.payloadInfoField = value;
                this.RaisePropertyChanged("PayloadInfo");
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(ProcessingType.PUSH)]
        public ProcessingType ProcessingType {
            get {
                return this.processingTypeField;
            }
            set {
                this.processingTypeField = value;
                this.RaisePropertyChanged("ProcessingType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string mpc {
            get {
                return this.mpcField;
            }
            set {
                this.mpcField = value;
                this.RaisePropertyChanged("mpc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/")]
    public partial class MessageInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime timestampField;
        
        private bool timestampFieldSpecified;
        
        private string messageIdField;
        
        private string refToMessageIdField;
        
        /// <remarks/>
        public System.DateTime Timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
                this.RaisePropertyChanged("Timestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TimestampSpecified {
            get {
                return this.timestampFieldSpecified;
            }
            set {
                this.timestampFieldSpecified = value;
                this.RaisePropertyChanged("TimestampSpecified");
            }
        }
        
        /// <remarks/>
        public string MessageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
                this.RaisePropertyChanged("MessageId");
            }
        }
        
        /// <remarks/>
        public string RefToMessageId {
            get {
                return this.refToMessageIdField;
            }
            set {
                this.refToMessageIdField = value;
                this.RaisePropertyChanged("RefToMessageId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/")]
    public partial class PartyInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private From fromField;
        
        private To toField;
        
        /// <remarks/>
        public From From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
                this.RaisePropertyChanged("From");
            }
        }
        
        /// <remarks/>
        public To To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
                this.RaisePropertyChanged("To");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/")]
    public partial class From : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PartyId partyIdField;
        
        private string roleField;
        
        /// <remarks/>
        public PartyId PartyId {
            get {
                return this.partyIdField;
            }
            set {
                this.partyIdField = value;
                this.RaisePropertyChanged("PartyId");
            }
        }
        
        /// <remarks/>
        public string Role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
                this.RaisePropertyChanged("Role");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/")]
    public partial class PartyId : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/")]
    public partial class To : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PartyId partyIdField;
        
        private string roleField;
        
        /// <remarks/>
        public PartyId PartyId {
            get {
                return this.partyIdField;
            }
            set {
                this.partyIdField = value;
                this.RaisePropertyChanged("PartyId");
            }
        }
        
        /// <remarks/>
        public string Role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
                this.RaisePropertyChanged("Role");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/")]
    public partial class CollaborationInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AgreementRef agreementRefField;
        
        private Service serviceField;
        
        private string actionField;
        
        private string conversationIdField;
        
        /// <remarks/>
        public AgreementRef AgreementRef {
            get {
                return this.agreementRefField;
            }
            set {
                this.agreementRefField = value;
                this.RaisePropertyChanged("AgreementRef");
            }
        }
        
        /// <remarks/>
        public Service Service {
            get {
                return this.serviceField;
            }
            set {
                this.serviceField = value;
                this.RaisePropertyChanged("Service");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string Action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
                this.RaisePropertyChanged("Action");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string ConversationId {
            get {
                return this.conversationIdField;
            }
            set {
                this.conversationIdField = value;
                this.RaisePropertyChanged("ConversationId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/")]
    public partial class AgreementRef : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private string pmodeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string pmode {
            get {
                return this.pmodeField;
            }
            set {
                this.pmodeField = value;
                this.RaisePropertyChanged("pmode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/")]
    public partial class Service : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/")]
    public partial class Property : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string typeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/")]
    public partial class PartInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Property[] partPropertiesField;
        
        private string hrefField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Property[] PartProperties {
            get {
                return this.partPropertiesField;
            }
            set {
                this.partPropertiesField = value;
                this.RaisePropertyChanged("PartProperties");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string href {
            get {
                return this.hrefField;
            }
            set {
                this.hrefField = value;
                this.RaisePropertyChanged("href");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/")]
    public enum ProcessingType {
        
        /// <remarks/>
        PUSH,
        
        /// <remarks/>
        PULL,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://eu.domibus.wsplugin/")]
    public partial class submitRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private LargePayloadType bodyloadField;
        
        private LargePayloadType[] payloadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public LargePayloadType bodyload {
            get {
                return this.bodyloadField;
            }
            set {
                this.bodyloadField = value;
                this.RaisePropertyChanged("bodyload");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("payload", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public LargePayloadType[] payload {
            get {
                return this.payloadField;
            }
            set {
                this.payloadField = value;
                this.RaisePropertyChanged("payload");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eu.domibus.wsplugin/")]
    public partial class LargePayloadType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] valueField;
        
        private string payloadIdField;
        
        private string contentTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string payloadId {
            get {
                return this.payloadIdField;
            }
            set {
                this.payloadIdField = value;
                this.RaisePropertyChanged("payloadId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string contentType {
            get {
                return this.contentTypeField;
            }
            set {
                this.contentTypeField = value;
                this.RaisePropertyChanged("contentType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class submitMessage {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/")]
        public EDelivery.SEOS.EDeliveryAS4Node.Messaging Messaging;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://eu.domibus.wsplugin/", Order=0)]
        public EDelivery.SEOS.EDeliveryAS4Node.submitRequest submitRequest;
        
        public submitMessage() {
        }
        
        public submitMessage(EDelivery.SEOS.EDeliveryAS4Node.Messaging Messaging, EDelivery.SEOS.EDeliveryAS4Node.submitRequest submitRequest) {
            this.Messaging = Messaging;
            this.submitRequest = submitRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class submitMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://eu.domibus.wsplugin/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("messageID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] submitResponse;
        
        public submitMessageResponse() {
        }
        
        public submitMessageResponse(string[] submitResponse) {
            this.submitResponse = submitResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://eu.domibus.wsplugin/")]
    public partial class retrieveMessageRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string messageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
                this.RaisePropertyChanged("messageID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://eu.domibus.wsplugin/")]
    public partial class retrieveMessageResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private LargePayloadType bodyloadField;
        
        private LargePayloadType[] payloadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public LargePayloadType bodyload {
            get {
                return this.bodyloadField;
            }
            set {
                this.bodyloadField = value;
                this.RaisePropertyChanged("bodyload");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("payload", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public LargePayloadType[] payload {
            get {
                return this.payloadField;
            }
            set {
                this.payloadField = value;
                this.RaisePropertyChanged("payload");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class retrieveMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://eu.domibus.wsplugin/", Order=0)]
        public EDelivery.SEOS.EDeliveryAS4Node.retrieveMessageRequest retrieveMessageRequest;
        
        public retrieveMessage() {
        }
        
        public retrieveMessage(EDelivery.SEOS.EDeliveryAS4Node.retrieveMessageRequest retrieveMessageRequest) {
            this.retrieveMessageRequest = retrieveMessageRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class retrieveMessageResponse1 {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/")]
        public EDelivery.SEOS.EDeliveryAS4Node.Messaging Messaging;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://eu.domibus.wsplugin/", Order=0)]
        public EDelivery.SEOS.EDeliveryAS4Node.retrieveMessageResponse retrieveMessageResponse;
        
        public retrieveMessageResponse1() {
        }
        
        public retrieveMessageResponse1(EDelivery.SEOS.EDeliveryAS4Node.Messaging Messaging, EDelivery.SEOS.EDeliveryAS4Node.retrieveMessageResponse retrieveMessageResponse) {
            this.Messaging = Messaging;
            this.retrieveMessageResponse = retrieveMessageResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://eu.domibus.wsplugin/")]
    public partial class listPendingMessagesRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageIdField;
        
        private string conversationIdField;
        
        private string refToMessageIdField;
        
        private string fromPartyIdField;
        
        private string finalRecipientField;
        
        private string originalSenderField;
        
        private System.DateTime receivedFromField;
        
        private bool receivedFromFieldSpecified;
        
        private System.DateTime receivedToField;
        
        private bool receivedToFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string messageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
                this.RaisePropertyChanged("messageId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string conversationId {
            get {
                return this.conversationIdField;
            }
            set {
                this.conversationIdField = value;
                this.RaisePropertyChanged("conversationId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string refToMessageId {
            get {
                return this.refToMessageIdField;
            }
            set {
                this.refToMessageIdField = value;
                this.RaisePropertyChanged("refToMessageId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string fromPartyId {
            get {
                return this.fromPartyIdField;
            }
            set {
                this.fromPartyIdField = value;
                this.RaisePropertyChanged("fromPartyId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string finalRecipient {
            get {
                return this.finalRecipientField;
            }
            set {
                this.finalRecipientField = value;
                this.RaisePropertyChanged("finalRecipient");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string originalSender {
            get {
                return this.originalSenderField;
            }
            set {
                this.originalSenderField = value;
                this.RaisePropertyChanged("originalSender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public System.DateTime receivedFrom {
            get {
                return this.receivedFromField;
            }
            set {
                this.receivedFromField = value;
                this.RaisePropertyChanged("receivedFrom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool receivedFromSpecified {
            get {
                return this.receivedFromFieldSpecified;
            }
            set {
                this.receivedFromFieldSpecified = value;
                this.RaisePropertyChanged("receivedFromSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public System.DateTime receivedTo {
            get {
                return this.receivedToField;
            }
            set {
                this.receivedToField = value;
                this.RaisePropertyChanged("receivedTo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool receivedToSpecified {
            get {
                return this.receivedToFieldSpecified;
            }
            set {
                this.receivedToFieldSpecified = value;
                this.RaisePropertyChanged("receivedToSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listPendingMessages {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://eu.domibus.wsplugin/", Order=0)]
        public EDelivery.SEOS.EDeliveryAS4Node.listPendingMessagesRequest listPendingMessagesRequest;
        
        public listPendingMessages() {
        }
        
        public listPendingMessages(EDelivery.SEOS.EDeliveryAS4Node.listPendingMessagesRequest listPendingMessagesRequest) {
            this.listPendingMessagesRequest = listPendingMessagesRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listPendingMessagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listPendingMessagesResponse", Namespace="http://eu.domibus.wsplugin/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("messageID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] listPendingMessagesResponse1;
        
        public listPendingMessagesResponse() {
        }
        
        public listPendingMessagesResponse(string[] listPendingMessagesResponse1) {
            this.listPendingMessagesResponse1 = listPendingMessagesResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServicePluginInterfaceChannel : EDelivery.SEOS.EDeliveryAS4Node.WebServicePluginInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServicePluginInterfaceClient : System.ServiceModel.ClientBase<EDelivery.SEOS.EDeliveryAS4Node.WebServicePluginInterface>, EDelivery.SEOS.EDeliveryAS4Node.WebServicePluginInterface {
        
        public WebServicePluginInterfaceClient() {
        }
        
        public WebServicePluginInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServicePluginInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServicePluginInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServicePluginInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EDelivery.SEOS.EDeliveryAS4Node.getMessageErrorsResponse EDelivery.SEOS.EDeliveryAS4Node.WebServicePluginInterface.getMessageErrors(EDelivery.SEOS.EDeliveryAS4Node.getMessageErrors request) {
            return base.Channel.getMessageErrors(request);
        }
        
        public EDelivery.SEOS.EDeliveryAS4Node.errorResultImpl[] getMessageErrors(EDelivery.SEOS.EDeliveryAS4Node.getErrorsRequest getErrorsRequest) {
            EDelivery.SEOS.EDeliveryAS4Node.getMessageErrors inValue = new EDelivery.SEOS.EDeliveryAS4Node.getMessageErrors();
            inValue.getErrorsRequest = getErrorsRequest;
            EDelivery.SEOS.EDeliveryAS4Node.getMessageErrorsResponse retVal = ((EDelivery.SEOS.EDeliveryAS4Node.WebServicePluginInterface)(this)).getMessageErrors(inValue);
            return retVal.getMessageErrorsResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EDelivery.SEOS.EDeliveryAS4Node.getMessageErrorsResponse> EDelivery.SEOS.EDeliveryAS4Node.WebServicePluginInterface.getMessageErrorsAsync(EDelivery.SEOS.EDeliveryAS4Node.getMessageErrors request) {
            return base.Channel.getMessageErrorsAsync(request);
        }
        
        public System.Threading.Tasks.Task<EDelivery.SEOS.EDeliveryAS4Node.getMessageErrorsResponse> getMessageErrorsAsync(EDelivery.SEOS.EDeliveryAS4Node.getErrorsRequest getErrorsRequest) {
            EDelivery.SEOS.EDeliveryAS4Node.getMessageErrors inValue = new EDelivery.SEOS.EDeliveryAS4Node.getMessageErrors();
            inValue.getErrorsRequest = getErrorsRequest;
            return ((EDelivery.SEOS.EDeliveryAS4Node.WebServicePluginInterface)(this)).getMessageErrorsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EDelivery.SEOS.EDeliveryAS4Node.getStatusResponse EDelivery.SEOS.EDeliveryAS4Node.WebServicePluginInterface.getStatus(EDelivery.SEOS.EDeliveryAS4Node.getStatus request) {
            return base.Channel.getStatus(request);
        }
        
        public System.Nullable<messageStatus> getStatus(EDelivery.SEOS.EDeliveryAS4Node.statusRequest statusRequest) {
            EDelivery.SEOS.EDeliveryAS4Node.getStatus inValue = new EDelivery.SEOS.EDeliveryAS4Node.getStatus();
            inValue.statusRequest = statusRequest;
            EDelivery.SEOS.EDeliveryAS4Node.getStatusResponse retVal = ((EDelivery.SEOS.EDeliveryAS4Node.WebServicePluginInterface)(this)).getStatus(inValue);
            return retVal.getStatusResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EDelivery.SEOS.EDeliveryAS4Node.getStatusResponse> EDelivery.SEOS.EDeliveryAS4Node.WebServicePluginInterface.getStatusAsync(EDelivery.SEOS.EDeliveryAS4Node.getStatus request) {
            return base.Channel.getStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<EDelivery.SEOS.EDeliveryAS4Node.getStatusResponse> getStatusAsync(EDelivery.SEOS.EDeliveryAS4Node.statusRequest statusRequest) {
            EDelivery.SEOS.EDeliveryAS4Node.getStatus inValue = new EDelivery.SEOS.EDeliveryAS4Node.getStatus();
            inValue.statusRequest = statusRequest;
            return ((EDelivery.SEOS.EDeliveryAS4Node.WebServicePluginInterface)(this)).getStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EDelivery.SEOS.EDeliveryAS4Node.submitMessageResponse EDelivery.SEOS.EDeliveryAS4Node.WebServicePluginInterface.submitMessage(EDelivery.SEOS.EDeliveryAS4Node.submitMessage request) {
            return base.Channel.submitMessage(request);
        }
        
        public string[] submitMessage(EDelivery.SEOS.EDeliveryAS4Node.Messaging Messaging, EDelivery.SEOS.EDeliveryAS4Node.submitRequest submitRequest) {
            EDelivery.SEOS.EDeliveryAS4Node.submitMessage inValue = new EDelivery.SEOS.EDeliveryAS4Node.submitMessage();
            inValue.Messaging = Messaging;
            inValue.submitRequest = submitRequest;
            EDelivery.SEOS.EDeliveryAS4Node.submitMessageResponse retVal = ((EDelivery.SEOS.EDeliveryAS4Node.WebServicePluginInterface)(this)).submitMessage(inValue);
            return retVal.submitResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EDelivery.SEOS.EDeliveryAS4Node.submitMessageResponse> EDelivery.SEOS.EDeliveryAS4Node.WebServicePluginInterface.submitMessageAsync(EDelivery.SEOS.EDeliveryAS4Node.submitMessage request) {
            return base.Channel.submitMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<EDelivery.SEOS.EDeliveryAS4Node.submitMessageResponse> submitMessageAsync(EDelivery.SEOS.EDeliveryAS4Node.Messaging Messaging, EDelivery.SEOS.EDeliveryAS4Node.submitRequest submitRequest) {
            EDelivery.SEOS.EDeliveryAS4Node.submitMessage inValue = new EDelivery.SEOS.EDeliveryAS4Node.submitMessage();
            inValue.Messaging = Messaging;
            inValue.submitRequest = submitRequest;
            return ((EDelivery.SEOS.EDeliveryAS4Node.WebServicePluginInterface)(this)).submitMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EDelivery.SEOS.EDeliveryAS4Node.retrieveMessageResponse1 EDelivery.SEOS.EDeliveryAS4Node.WebServicePluginInterface.retrieveMessage(EDelivery.SEOS.EDeliveryAS4Node.retrieveMessage request) {
            return base.Channel.retrieveMessage(request);
        }
        
        public EDelivery.SEOS.EDeliveryAS4Node.Messaging retrieveMessage(EDelivery.SEOS.EDeliveryAS4Node.retrieveMessageRequest retrieveMessageRequest, out EDelivery.SEOS.EDeliveryAS4Node.retrieveMessageResponse retrieveMessageResponse) {
            EDelivery.SEOS.EDeliveryAS4Node.retrieveMessage inValue = new EDelivery.SEOS.EDeliveryAS4Node.retrieveMessage();
            inValue.retrieveMessageRequest = retrieveMessageRequest;
            EDelivery.SEOS.EDeliveryAS4Node.retrieveMessageResponse1 retVal = ((EDelivery.SEOS.EDeliveryAS4Node.WebServicePluginInterface)(this)).retrieveMessage(inValue);
            retrieveMessageResponse = retVal.retrieveMessageResponse;
            return retVal.Messaging;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EDelivery.SEOS.EDeliveryAS4Node.retrieveMessageResponse1> EDelivery.SEOS.EDeliveryAS4Node.WebServicePluginInterface.retrieveMessageAsync(EDelivery.SEOS.EDeliveryAS4Node.retrieveMessage request) {
            return base.Channel.retrieveMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<EDelivery.SEOS.EDeliveryAS4Node.retrieveMessageResponse1> retrieveMessageAsync(EDelivery.SEOS.EDeliveryAS4Node.retrieveMessageRequest retrieveMessageRequest) {
            EDelivery.SEOS.EDeliveryAS4Node.retrieveMessage inValue = new EDelivery.SEOS.EDeliveryAS4Node.retrieveMessage();
            inValue.retrieveMessageRequest = retrieveMessageRequest;
            return ((EDelivery.SEOS.EDeliveryAS4Node.WebServicePluginInterface)(this)).retrieveMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EDelivery.SEOS.EDeliveryAS4Node.listPendingMessagesResponse EDelivery.SEOS.EDeliveryAS4Node.WebServicePluginInterface.listPendingMessages(EDelivery.SEOS.EDeliveryAS4Node.listPendingMessages request) {
            return base.Channel.listPendingMessages(request);
        }
        
        public string[] listPendingMessages(EDelivery.SEOS.EDeliveryAS4Node.listPendingMessagesRequest listPendingMessagesRequest) {
            EDelivery.SEOS.EDeliveryAS4Node.listPendingMessages inValue = new EDelivery.SEOS.EDeliveryAS4Node.listPendingMessages();
            inValue.listPendingMessagesRequest = listPendingMessagesRequest;
            EDelivery.SEOS.EDeliveryAS4Node.listPendingMessagesResponse retVal = ((EDelivery.SEOS.EDeliveryAS4Node.WebServicePluginInterface)(this)).listPendingMessages(inValue);
            return retVal.listPendingMessagesResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EDelivery.SEOS.EDeliveryAS4Node.listPendingMessagesResponse> EDelivery.SEOS.EDeliveryAS4Node.WebServicePluginInterface.listPendingMessagesAsync(EDelivery.SEOS.EDeliveryAS4Node.listPendingMessages request) {
            return base.Channel.listPendingMessagesAsync(request);
        }
        
        public System.Threading.Tasks.Task<EDelivery.SEOS.EDeliveryAS4Node.listPendingMessagesResponse> listPendingMessagesAsync(EDelivery.SEOS.EDeliveryAS4Node.listPendingMessagesRequest listPendingMessagesRequest) {
            EDelivery.SEOS.EDeliveryAS4Node.listPendingMessages inValue = new EDelivery.SEOS.EDeliveryAS4Node.listPendingMessages();
            inValue.listPendingMessagesRequest = listPendingMessagesRequest;
            return ((EDelivery.SEOS.EDeliveryAS4Node.WebServicePluginInterface)(this)).listPendingMessagesAsync(inValue);
        }
    }
}
