//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDelivery.UserStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public Login()
        {
        }
    
        //public int Id { get; set; }
        //public string UserName { get; set; }
        //public string Email { get; set; }
        //public bool EmailConfirmed { get; set; }
        //public string PasswordHash { get; set; }
        //public string SecurityStamp { get; set; }
        //public string PhoneNumber { get; set; }
        //public bool PhoneNumberConfirmed { get; set; }
        //public bool TwoFactorEnabled { get; set; }
        //public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        //public bool LockoutEnabled { get; set; }
        //public int AccessFailedCount { get; set; }
        public System.Guid ElectronicSubjectId { get; set; }
        public string ElectronicSubjectName { get; set; }
        public bool IsActive { get; set; }
    
        //public virtual ICollection<ExternalLogin> Logins { get; set; }
        //public virtual ICollection<LoginsClaim> Claims { get; set; }
        //public virtual ICollection<LoginsRole> Roles { get; set; }
    }
}
