//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ED.AdminPanel.Blazor.Pages.Reports {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DelayedMessagesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DelayedMessagesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ED.AdminPanel.Blazor.Pages.Reports.DelayedMessagesResources", typeof(DelayedMessagesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Експорт.
        /// </summary>
        public static string BtnExport {
            get {
                return ResourceManager.GetString("BtnExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Търси.
        /// </summary>
        public static string BtnSearch {
            get {
                return ResourceManager.GetString("BtnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показване на съобщения, изпратени преди {0} ({1}), които в настоящия момент все още на са връчени.
        /// </summary>
        public static string ColumnAll {
            get {
                return ResourceManager.GetString("ColumnAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата на изпращане.
        /// </summary>
        public static string ColumnDateSent {
            get {
                return ResourceManager.GetString("ColumnDateSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дни на забавяне на връчването.
        /// </summary>
        public static string ColumnDelay {
            get {
                return ResourceManager.GetString("ColumnDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email получател.
        /// </summary>
        public static string ColumnEmailRecipient {
            get {
                return ResourceManager.GetString("ColumnEmailRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email връчител.
        /// </summary>
        public static string ColumnEmailSender {
            get {
                return ResourceManager.GetString("ColumnEmailSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Съобщение.
        /// </summary>
        public static string ColumnMessageSubject {
            get {
                return ResourceManager.GetString("ColumnMessageSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профил получател.
        /// </summary>
        public static string ColumnProfileRecipient {
            get {
                return ResourceManager.GetString("ColumnProfileRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получател.
        /// </summary>
        public static string ColumnRecipient {
            get {
                return ResourceManager.GetString("ColumnRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Връчител.
        /// </summary>
        public static string ColumnSender {
            get {
                return ResourceManager.GetString("ColumnSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Целева група получател.
        /// </summary>
        public static string ColumnTargetGroupRecipient {
            get {
                return ResourceManager.GetString("ColumnTargetGroupRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неделя.
        /// </summary>
        public static string DayOfWeek_0 {
            get {
                return ResourceManager.GetString("DayOfWeek_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Понеделник.
        /// </summary>
        public static string DayOfWeek_1 {
            get {
                return ResourceManager.GetString("DayOfWeek_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вторник.
        /// </summary>
        public static string DayOfWeek_2 {
            get {
                return ResourceManager.GetString("DayOfWeek_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сряда.
        /// </summary>
        public static string DayOfWeek_3 {
            get {
                return ResourceManager.GetString("DayOfWeek_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Четвъртък.
        /// </summary>
        public static string DayOfWeek_4 {
            get {
                return ResourceManager.GetString("DayOfWeek_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Петък.
        /// </summary>
        public static string DayOfWeek_5 {
            get {
                return ResourceManager.GetString("DayOfWeek_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Събота.
        /// </summary>
        public static string DayOfWeek_6 {
            get {
                return ResourceManager.GetString("DayOfWeek_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забавяне на отварянето с брой дни.
        /// </summary>
        public static string FormDelay {
            get {
                return ResourceManager.GetString("FormDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получател.
        /// </summary>
        public static string FormProfile {
            get {
                return ResourceManager.GetString("FormProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Целева група.
        /// </summary>
        public static string FormTargetGroup {
            get {
                return ResourceManager.GetString("FormTargetGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Няма съобщения с забавено връчване.
        /// </summary>
        public static string NoItems {
            get {
                return ResourceManager.GetString("NoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активиран.
        /// </summary>
        public static string ProfileActivated {
            get {
                return ResourceManager.GetString("ProfileActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неактивиран.
        /// </summary>
        public static string ProfileNotActivated {
            get {
                return ResourceManager.GetString("ProfileNotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Справка за неотворени съобщения в определен период.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
