//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ED.AdminPanel.Blazor.Pages.Reports {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReceivedMessagesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReceivedMessagesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ED.AdminPanel.Blazor.Pages.Reports.ReceivedMessagesResources", typeof(ReceivedMessagesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Експорт.
        /// </summary>
        public static string BtnExport {
            get {
                return ResourceManager.GetString("BtnExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Търси.
        /// </summary>
        public static string BtnSearch {
            get {
                return ResourceManager.GetString("BtnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показване на изпратени съобщения, които са получени в периода {0} - {1}.
        /// </summary>
        public static string ColumnAll {
            get {
                return ResourceManager.GetString("ColumnAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата на получаване.
        /// </summary>
        public static string ColumnDateReceived {
            get {
                return ResourceManager.GetString("ColumnDateReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата на изпращане.
        /// </summary>
        public static string ColumnDateSent {
            get {
                return ResourceManager.GetString("ColumnDateSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование.
        /// </summary>
        public static string ColumnMessageSubject {
            get {
                return ResourceManager.GetString("ColumnMessageSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профил получател.
        /// </summary>
        public static string ColumnProfileRecipient {
            get {
                return ResourceManager.GetString("ColumnProfileRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профил подател.
        /// </summary>
        public static string ColumnProfileSender {
            get {
                return ResourceManager.GetString("ColumnProfileSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получател.
        /// </summary>
        public static string ColumnRecipient {
            get {
                return ResourceManager.GetString("ColumnRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подател.
        /// </summary>
        public static string ColumnSender {
            get {
                return ResourceManager.GetString("ColumnSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Целева група получател.
        /// </summary>
        public static string ColumnTargetGroupRecipient {
            get {
                return ResourceManager.GetString("ColumnTargetGroupRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Целева група подател.
        /// </summary>
        public static string ColumnTargetGroupSender {
            get {
                return ResourceManager.GetString("ColumnTargetGroupSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to От дата на получаване.
        /// </summary>
        public static string FormFromDate {
            get {
                return ResourceManager.GetString("FormFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получател.
        /// </summary>
        public static string FormRecipientProfile {
            get {
                return ResourceManager.GetString("FormRecipientProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подател.
        /// </summary>
        public static string FormSenderProfile {
            get {
                return ResourceManager.GetString("FormSenderProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to До дата на получаване.
        /// </summary>
        public static string FormToDate {
            get {
                return ResourceManager.GetString("FormToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Няма съобщения.
        /// </summary>
        public static string NoItems {
            get {
                return ResourceManager.GetString("NoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активиран.
        /// </summary>
        public static string ProfileActivated {
            get {
                return ResourceManager.GetString("ProfileActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неактивиран.
        /// </summary>
        public static string ProfileNotActivated {
            get {
                return ResourceManager.GetString("ProfileNotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Справка получени съобщения.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
