//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ED.AdminPanel.Blazor.Pages.Reports {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TicketsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TicketsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ED.AdminPanel.Blazor.Pages.Reports.TicketsResources", typeof(TicketsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Експорт.
        /// </summary>
        public static string BtnExport {
            get {
                return ResourceManager.GetString("BtnExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Търси.
        /// </summary>
        public static string BtnSearch {
            get {
                return ResourceManager.GetString("BtnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Справка административни актове за {0}.
        /// </summary>
        public static string ColumnAll {
            get {
                return ResourceManager.GetString("ColumnAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ден.
        /// </summary>
        public static string FormReportDate {
            get {
                return ResourceManager.GetString("FormReportDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активни профили.
        /// </summary>
        public static string LabelDailyActiveProfiles {
            get {
                return ResourceManager.GetString("LabelDailyActiveProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to НП - ФЛ.
        /// </summary>
        public static string LabelDailyIndividualPenalDecrees {
            get {
                return ResourceManager.GetString("LabelDailyIndividualPenalDecrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фиш - ФЛ.
        /// </summary>
        public static string LabelDailyIndividualTickets {
            get {
                return ResourceManager.GetString("LabelDailyIndividualTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общо (НП + фиш) - ФЛ.
        /// </summary>
        public static string LabelDailyIndividualTotalTickets {
            get {
                return ResourceManager.GetString("LabelDailyIndividualTotalTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to НП - ЮЛ.
        /// </summary>
        public static string LabelDailyLegalEntityPenalDecrees {
            get {
                return ResourceManager.GetString("LabelDailyLegalEntityPenalDecrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фиш - ЮЛ.
        /// </summary>
        public static string LabelDailyLegalEntityTickets {
            get {
                return ResourceManager.GetString("LabelDailyLegalEntityTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общо (НП + фиш) - ЮЛ.
        /// </summary>
        public static string LabelDailyLegalEntityTotalTickets {
            get {
                return ResourceManager.GetString("LabelDailyLegalEntityTotalTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нотификации Общо.
        /// </summary>
        public static string LabelDailyNotifications {
            get {
                return ResourceManager.GetString("LabelDailyNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имейл.
        /// </summary>
        public static string LabelDailyNotificationsByEmail {
            get {
                return ResourceManager.GetString("LabelDailyNotificationsByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        public static string LabelDailyNotificationsByPhone {
            get {
                return ResourceManager.GetString("LabelDailyNotificationsByPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пасивни профили.
        /// </summary>
        public static string LabelDailyPassiveProfiles {
            get {
                return ResourceManager.GetString("LabelDailyPassiveProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Връчени НП - ФЛ.
        /// </summary>
        public static string LabelDailyReceivedIndividualPenalDecrees {
            get {
                return ResourceManager.GetString("LabelDailyReceivedIndividualPenalDecrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Връчени Фиш - ФЛ.
        /// </summary>
        public static string LabelDailyReceivedIndividualTickets {
            get {
                return ResourceManager.GetString("LabelDailyReceivedIndividualTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Връчени НП - ЮЛ.
        /// </summary>
        public static string LabelDailyReceivedLegalEntityPenalDecrees {
            get {
                return ResourceManager.GetString("LabelDailyReceivedLegalEntityPenalDecrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Връчени Фиш - ЮЛ.
        /// </summary>
        public static string LabelDailyReceivedLegalEntityTickets {
            get {
                return ResourceManager.GetString("LabelDailyReceivedLegalEntityTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Брой връчени през ССЕВ.
        /// </summary>
        public static string LabelDailyReceivedTickets {
            get {
                return ResourceManager.GetString("LabelDailyReceivedTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Брой получени в ССЕВ.
        /// </summary>
        public static string LabelDailyTickets {
            get {
                return ResourceManager.GetString("LabelDailyTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Брой адм. актове.
        /// </summary>
        public static string LabelTotalTickets {
            get {
                return ResourceManager.GetString("LabelTotalTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Справка административни актове.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
