//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDeliveryResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ARIA {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ARIA() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EDeliveryResources.ARIA", typeof(ARIA).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оперативна програма „Административен капацитет”.
        /// </summary>
        public static string AltFooterFlag {
            get {
                return ResourceManager.GetString("AltFooterFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оперативна програма „Добро управление”, съфинансирана от Европейския съюз.
        /// </summary>
        public static string AltFooterFlag2 {
            get {
                return ResourceManager.GetString("AltFooterFlag2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Система за сигурно електронно връчване - Начална страница.
        /// </summary>
        public static string AltLogo {
            get {
                return ResourceManager.GetString("AltLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Времева квитанция.
        /// </summary>
        public static string AltMessageTimestamp {
            get {
                return ResourceManager.GetString("AltMessageTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изтриване.
        /// </summary>
        public static string AltProfileAdministrationDelete {
            get {
                return ResourceManager.GetString("AltProfileAdministrationDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редакция.
        /// </summary>
        public static string AltProfileAdministrationEdit {
            get {
                return ResourceManager.GetString("AltProfileAdministrationEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изтриване.
        /// </summary>
        public static string AltProfileGroupMembersDelete {
            get {
                return ResourceManager.GetString("AltProfileGroupMembersDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Експорт.
        /// </summary>
        public static string AltProfileHistoryExport {
            get {
                return ResourceManager.GetString("AltProfileHistoryExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изтрий файл.
        /// </summary>
        public static string AltStorageDelete {
            get {
                return ResourceManager.GetString("AltStorageDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свали файл.
        /// </summary>
        public static string AltStorageDownload {
            get {
                return ResourceManager.GetString("AltStorageDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл със зловреден код.
        /// </summary>
        public static string AltStorageMalicious {
            get {
                return ResourceManager.GetString("AltStorageMalicious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Непроверен файл.
        /// </summary>
        public static string AltStorageNeutral {
            get {
                return ResourceManager.GetString("AltStorageNeutral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверен файл.
        /// </summary>
        public static string AltStorageOk {
            get {
                return ResourceManager.GetString("AltStorageOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Качване на файл.
        /// </summary>
        public static string AltStorageUpload {
            get {
                return ResourceManager.GetString("AltStorageUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изтриване.
        /// </summary>
        public static string AltTranslationsListDelete {
            get {
                return ResourceManager.GetString("AltTranslationsListDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Преглед.
        /// </summary>
        public static string AltTranslationsListView {
            get {
                return ResourceManager.GetString("AltTranslationsListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Затваряне на диалога.
        /// </summary>
        public static string LabelDialogCloseBtn {
            get {
                return ResourceManager.GetString("LabelDialogCloseBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Търсене на получател.
        /// </summary>
        public static string LabelMessageRecipientSelect2 {
            get {
                return ResourceManager.GetString("LabelMessageRecipientSelect2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Техническо поле за файл.
        /// </summary>
        public static string LabelRegisterLegalEntityFile {
            get {
                return ResourceManager.GetString("LabelRegisterLegalEntityFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Техническо поле за файл.
        /// </summary>
        public static string LabelTemplateFile {
            get {
                return ResourceManager.GetString("LabelTemplateFile", resourceCulture);
            }
        }
    }
}
