//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDeliveryResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EDeliveryResources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сигурни ли сте, че желаете да затворите страницата?.
        /// </summary>
        public static string ConfigrmLeaveMessage {
            get {
                return ResourceManager.GetString("ConfigrmLeaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вече има регистриран потребител със същия e-mail адрес!.
        /// </summary>
        public static string EmailAlredyRegistered {
            get {
                return ResourceManager.GetString("EmailAlredyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо е да приемете &apos;Условия на политиката за поверителност и защита на данните&apos;, за да направите Вашата регистрация!.
        /// </summary>
        public static string ErrorAcceptGDPRAgreement {
            get {
                return ResourceManager.GetString("ErrorAcceptGDPRAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо е да приемете &apos;Условия за ползвате на системата за сигурно електронно връчване&apos;, за да направите Вашата регистрация!.
        /// </summary>
        public static string ErrorAcceptLicenceAgreement {
            get {
                return ResourceManager.GetString("ErrorAcceptLicenceAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Системна грешка! Потребителят не може да бъде създаден. Моля свържете се с администратор или опитайте по-късно..
        /// </summary>
        public static string ErrorCanNotCreateUser {
            get {
                return ResourceManager.GetString("ErrorCanNotCreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Достъпът до профила не може да бъде даден в момента! Моля свържете се с администратор за повече информация..
        /// </summary>
        public static string ErrorCanNotGrantAccess {
            get {
                return ResourceManager.GetString("ErrorCanNotGrantAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профилните данни не могат да бъдат актуализирани в момента! Моля опитайте по-късно или се свържете с администратор за помощ..
        /// </summary>
        public static string ErrorCanNotUpdateProfile {
            get {
                return ResourceManager.GetString("ErrorCanNotUpdateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поради системна грешка заявка за превод на съобщението не може да бъде създадена..
        /// </summary>
        public static string ErrorCantCreateTranslation {
            get {
                return ResourceManager.GetString("ErrorCantCreateTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Съобщението не може да бъде изпратено в момента! Моля опитайте по-късно или се свържете с администратор за помощ..
        /// </summary>
        public static string ErrorCantSendDocument {
            get {
                return ResourceManager.GetString("ErrorCantSendDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Възникна грашка в комуникацията с услугата за TimeStamp! Съобщението не може да бъде изпратено в момента! Моля, опитайте по-късно!.
        /// </summary>
        public static string ErrorCantSendDocumentTimestampIssues {
            get {
                return ResourceManager.GetString("ErrorCantSendDocumentTimestampIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Грешка! Файлът не може да бъде качен на сървъра!.
        /// </summary>
        public static string ErrorCantUploadFile {
            get {
                return ResourceManager.GetString("ErrorCantUploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Грешка! Вашето заявление не може да бъде записано! В системате вече съществува регистрирано лице с ЕИК {0}!.
        /// </summary>
        public static string ErrorEIKAlreadyRegistered {
            get {
                return ResourceManager.GetString("ErrorEIKAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вече има съществуваща група с това име, моля изберете друго..
        /// </summary>
        public static string ErrorExistingGroupName {
            get {
                return ResourceManager.GetString("ErrorExistingGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невалиден код за достъп.
        /// </summary>
        public static string ErrorInvalidAccessCode {
            get {
                return ResourceManager.GetString("ErrorInvalidAccessCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текуща парола не е вярна!.
        /// </summary>
        public static string ErrorInvalidCurrentPassword {
            get {
                return ResourceManager.GetString("ErrorInvalidCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Липсващи или невалидни данни!.
        /// </summary>
        public static string ErrorInvalidData {
            get {
                return ResourceManager.GetString("ErrorInvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невалиден формат на ЕГН!.
        /// </summary>
        public static string ErrorInvalidEGN {
            get {
                return ResourceManager.GetString("ErrorInvalidEGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некоректен ЕГН параметър! .
        /// </summary>
        public static string ErrorInvalidEGNParam {
            get {
                return ResourceManager.GetString("ErrorInvalidEGNParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля въведете валиден email адрес!.
        /// </summary>
        public static string ErrorInvalidEmail {
            get {
                return ResourceManager.GetString("ErrorInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля, уверете се, че паролата  Ви съдържа поне една цифра (0-9), поне една главна и една малка буква и поне един символ, различен от буква и цифра!.
        /// </summary>
        public static string ErrorInvalidPassword {
            get {
                return ResourceManager.GetString("ErrorInvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невалидни или липсващи данни!.
        /// </summary>
        public static string ErrorInvalidPdfFormData {
            get {
                return ResourceManager.GetString("ErrorInvalidPdfFormData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля въведете валиден телефонен номер!.
        /// </summary>
        public static string ErrorInvalidPhone {
            get {
                return ResourceManager.GetString("ErrorInvalidPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неуспешна идентификация. Възникна проблем с разчитането на Вашия КЕП.&lt;br/&gt;
        ///Моля, извадете устройството, рестартирайте браузъра, поставете устройството и опитайте отново. Ако проблемите продължават, свържете с администратора на системата. STS съобщение: {0}.
        /// </summary>
        public static string ErrorKepAuthenticationFailed {
            get {
                return ResourceManager.GetString("ErrorKepAuthenticationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Грешка в модула за единна автентикация с КЕП. Моля свържете се с администратор за отстраняване на проблема! STS съобщение: {0}. .
        /// </summary>
        public static string ErrorKepFailedInvalidResponse {
            get {
                return ResourceManager.GetString("ErrorKepFailedInvalidResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Търсеното юридическо лице не е намерено в системата!.
        /// </summary>
        public static string ErrorLegalNotFound {
            get {
                return ResourceManager.GetString("ErrorLegalNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За ЕИК {0} вече има подадено заявление за регистрация, което е в процес на обработка! .
        /// </summary>
        public static string ErrorLegalPedingRegistration {
            get {
                return ResourceManager.GetString("ErrorLegalPedingRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Грешка при вход с Електронна Идентичност! Моля, свържете се с администратор за отстраняване на проблема!.
        /// </summary>
        public static string ErrorLoginEID {
            get {
                return ResourceManager.GetString("ErrorLoginEID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невалидни потребителско име / парола!.
        /// </summary>
        public static string ErrorLoginInvalidCredentials {
            get {
                return ResourceManager.GetString("ErrorLoginInvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профилът е деактивиран. За повторна активация на профила свържете се с администратор!.
        /// </summary>
        public static string ErrorLoginIsDeactivated {
            get {
                return ResourceManager.GetString("ErrorLoginIsDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Грешка при опит за автентикация с КЕП. Моля, свържете се с администратор за отстраняване на проблема..
        /// </summary>
        public static string ErrorLoginKEP {
            get {
                return ResourceManager.GetString("ErrorLoginKEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въвели сте няколко пъти грешна парола, поради което потребителят временно се заключва!.
        /// </summary>
        public static string ErrorLoginLockedOut {
            get {
                return ResourceManager.GetString("ErrorLoginLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вашият профил в системата за сигурно електронно връчване НЕ е е активиран. .
        /// </summary>
        public static string ErrorLoginNoActiveProfiles {
            get {
                return ResourceManager.GetString("ErrorLoginNoActiveProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стигнали сте максималния брой на архивирани преводи за съобщение!.
        /// </summary>
        public static string ErrorMaxArchivedMessageTranslations {
            get {
                return ResourceManager.GetString("ErrorMaxArchivedMessageTranslations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максималният размер на прикачения документ трябва да не надвишава {0} МБ!.
        /// </summary>
        public static string ErrorMaxFileLength {
            get {
                return ResourceManager.GetString("ErrorMaxFileLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето може да съдържа само букви на кирилица (А-Я) и тире!.
        /// </summary>
        public static string ErrorMessageCyrilicRequired {
            get {
                return ResourceManager.GetString("ErrorMessageCyrilicRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето трябва да е с дължина максимум {1} символа.
        /// </summary>
        public static string ErrorMessageFieldLength {
            get {
                return ResourceManager.GetString("ErrorMessageFieldLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въведеният идентификатор не е валидно ЕГН или ЛНЧ..
        /// </summary>
        public static string ErrorMessageInvalidEGNorLNCh {
            get {
                return ResourceManager.GetString("ErrorMessageInvalidEGNorLNCh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задължението, което се опитвате да достъпите, не беше открито или е вече платено!.
        /// </summary>
        public static string ErrorObligationNotFound {
            get {
                return ResourceManager.GetString("ErrorObligationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данните на страницата са неактуални. Моля опреснете екрана и повторете операцията!.
        /// </summary>
        public static string ErrorOldData {
            get {
                return ResourceManager.GetString("ErrorOldData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нямате достъп до ресурсът, който опитвате да достъпите!.
        /// </summary>
        public static string ErrorPageForbidden {
            get {
                return ResourceManager.GetString("ErrorPageForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ресурсът, който опитвате да достъпите, не беше открит!.
        /// </summary>
        public static string ErrorPageNotFound {
            get {
                return ResourceManager.GetString("ErrorPageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паролата и паролата повторно не съвпадат!.
        /// </summary>
        public static string ErrorPasswordConfirm {
            get {
                return ResourceManager.GetString("ErrorPasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паролата трябва да е с дължина минимум {2} символа.
        /// </summary>
        public static string ErrorPasswordLength {
            get {
                return ResourceManager.GetString("ErrorPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля, прикачете PDF документ!.
        /// </summary>
        public static string ErrorPdfRequired {
            get {
                return ResourceManager.GetString("ErrorPdfRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Търсенето физическо лице не е намерено в системата!.
        /// </summary>
        public static string ErrorPersonNotFound {
            get {
                return ResourceManager.GetString("ErrorPersonNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изпращането и получаването на съобщения не е активно за този профил!.
        /// </summary>
        public static string ErrorProfileIsReadOnly {
            get {
                return ResourceManager.GetString("ErrorProfileIsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получаването на съобщения не е активно за профила, към който искате да изпратите!.
        /// </summary>
        public static string ErrorProfileOfReceiverIsReadOnly {
            get {
                return ResourceManager.GetString("ErrorProfileOfReceiverIsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Електронният подпис на формата за регистрация е невалиден!.
        /// </summary>
        public static string ErrorRegisterCanNotValidateSignature {
            get {
                return ResourceManager.GetString("ErrorRegisterCanNotValidateSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Електронният подпис е с изтекла валидност!.
        /// </summary>
        public static string ErrorRegisterCertificateExpired {
            get {
                return ResourceManager.GetString("ErrorRegisterCertificateExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въведеният e-mail адрес трябва да съвпада с e-mail адреса от формата за регистрация!.
        /// </summary>
        public static string ErrorRegisterEmailMismatch {
            get {
                return ResourceManager.GetString("ErrorRegisterEmailMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Интегритетът на формата за регистрация е нарушен!.
        /// </summary>
        public static string ErrorRegisterInvalidIntegrity {
            get {
                return ResourceManager.GetString("ErrorRegisterInvalidIntegrity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въведеният телефонен номер трябва да съвпада с телефонния номер от формата за регистрация!.
        /// </summary>
        public static string ErrorRegisterPhoneNumberMismatch {
            get {
                return ResourceManager.GetString("ErrorRegisterPhoneNumberMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невалидни потребителско име / парола на представител!.
        /// </summary>
        public static string ErrorRegisterRepresentativeInvalidCredentials {
            get {
                return ResourceManager.GetString("ErrorRegisterRepresentativeInvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребителят, с който опитвате да направите регистрация, не е регистриран в системата!.
        /// </summary>
        public static string ErrorRegisterRepresentativeNotExists {
            get {
                return ResourceManager.GetString("ErrorRegisterRepresentativeNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето е задължително!.
        /// </summary>
        public static string ErrorRequired {
            get {
                return ResourceManager.GetString("ErrorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля, изберете дали ще използвате КЕП или eID за удостоверяване на Вашата регистрация!.
        /// </summary>
        public static string ErrorRequiredChooseRegistration {
            get {
                return ResourceManager.GetString("ErrorRequiredChooseRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Системна грешка! Операцията не може да бъде извършена в момента. Моля свържете се с администратор или опитайте по-късно..
        /// </summary>
        public static string ErrorSystemGeneral {
            get {
                return ResourceManager.GetString("ErrorSystemGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребителското име трябва да е не по-дълго от {1} символа!.
        /// </summary>
        public static string ErrorUserNameLength {
            get {
                return ResourceManager.GetString("ErrorUserNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Грешка в отговора на Валидиращ Орган! Моля, свържете се с администратор за отстраняване на проблема!.
        /// </summary>
        public static string InvalidEIDResponse {
            get {
                return ResourceManager.GetString("InvalidEIDResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Юридическото лице вече има активна регистрация в системата! За повече информация и промяна на данните, моля свържете се с администратор на системата!.
        /// </summary>
        public static string LegalPersonAlreadyRegisteredAndActivated {
            get {
                return ResourceManager.GetString("LegalPersonAlreadyRegisteredAndActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неуспешен опит за автентикация пред Автентикиращият орган! Моля, опитайте отново или изберете друг метод за вход!.
        /// </summary>
        public static string NotAuthenticatedByThirdParty {
            get {
                return ResourceManager.GetString("NotAuthenticatedByThirdParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Няма данни в ГРАО за текущия профил!.
        /// </summary>
        public static string ProfileNamesSyncGraoNoData {
            get {
                return ResourceManager.GetString("ProfileNamesSyncGraoNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В момента няма връзка с ГРАО! Моля, опитайте по-късно..
        /// </summary>
        public static string ProfileNamesSyncGraoServiceUnavailable {
            get {
                return ResourceManager.GetString("ProfileNamesSyncGraoServiceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Грешка! Операцията не може да бъде изпълнена за текущия профил!.
        /// </summary>
        public static string ProfileNamesSyncInvalidProfile {
            get {
                return ResourceManager.GetString("ProfileNamesSyncInvalidProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Грешка! Избраният формат на файла не е валиден за тази операция! Моля изберете попълена PDF бланка за регистрация!.
        /// </summary>
        public static string RegisterWithFormInvalidDocumentFormat {
            get {
                return ResourceManager.GetString("RegisterWithFormInvalidDocumentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Грешка! Невалиден или грешен ЕИК {0}.
        /// </summary>
        public static string RegisterWithFormInvalidSubjectIdentifier {
            get {
                return ResourceManager.GetString("RegisterWithFormInvalidSubjectIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Грешка! Има съществуващ профил в системата с ЕИК {0}. Не може да бъде направена регистрация!.
        /// </summary>
        public static string RegisterWithFormSubjectAlreadyExists {
            get {
                return ResourceManager.GetString("RegisterWithFormSubjectAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За съжаление все още нямате регистрация в нашата система. Моля, направере си регистрация и опитайте отново..
        /// </summary>
        public static string UserDoesNotExistsInTheSystem {
            get {
                return ResourceManager.GetString("UserDoesNotExistsInTheSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вече има регистриран потребител със същото потребителско име. .
        /// </summary>
        public static string UsernameAlredyRegistered {
            get {
                return ResourceManager.GetString("UsernameAlredyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вече има регистриран потребител с това потребителско име или e-mail адрес!.
        /// </summary>
        public static string UserOrEmailAlredyRegistered {
            get {
                return ResourceManager.GetString("UserOrEmailAlredyRegistered", resourceCulture);
            }
        }
    }
}
