//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDeliveryResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Help {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Help() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EDeliveryResources.Help", typeof(Help).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;tab_box_4&quot; class=&quot;tab-box&quot;&gt;
        ///    &lt;div class=&quot;tab-box-content&quot;&gt;
        ///        &lt;div class=&quot;content-wrapper message-box&quot;&gt;
        ///            &lt;h2&gt;Изпращане и получаване на съобщение &lt;/h2&gt;
        ///            &lt;p&gt;За изпращане на съобщение, потребителят трябва да избере бутон „Вход“ и да влезе в профила си чрез КЕП, чрез ПИК на НАП или чрез ПИК на НОИ, след което се отваря началният екран на Системата за сигурно електронно връчване (Фигура 4.1).&lt;/p&gt;
        ///            &lt;figure&gt;
        ///                &lt;img src=&quot;/Content/img/pixel.gif&quot; d [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;tab_box_5&quot; class=&quot;tab-box&quot;&gt;
        ///    &lt;div class=&quot;tab-box-content&quot;&gt;
        ///        &lt;div class=&quot;content-wrapper message-box&quot;&gt;
        ///            &lt;h2&gt;Администриране на профила&lt;/h2&gt;
        ///            &lt;p&gt;Чрез менюто „Администриране на профила“ потребителите могат да създават свои профилни групи, да конфигурират профила си, да получат статистика за достъп и да променят настройките в своя профил (Фигура 5.1).&lt;/p&gt;
        ///            &lt;figure&gt;
        ///                &lt;img src=&quot;/Content/img/pixel.gif&quot; data-src=&quot;5_1.jpeg&quot; class=&quot;lazy&quot; alt=&quot;Фиг [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;tab_box_1&quot; class=&quot;tab-box active&quot;&gt;
        ///    &lt;div class=&quot;tab-box-content&quot;&gt;
        ///        &lt;div class=&quot;content-wrapper message-box&quot;&gt;
        ///            &lt;h2&gt;Регистрация на физическо лице с ПИК на НОИ&lt;/h2&gt;
        ///            &lt;p&gt;За да се регистрирате с персонален идентификационен код на НОИ, е необходимо да имате такъв. Ако нямате издаден, може да се запознаете с процедурата за получаване на ПИК на адрес: &lt;a href=&quot;https://www.nssi.bg/&quot; rel=&quot;noopener&quot; target=&quot;_blank&quot;&gt;www.nssi.bg&lt;/a&gt;&lt;/p&gt;
        ///            &lt;p&gt;Отворете &lt;a href=&quot;https [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Register1 {
            get {
                return ResourceManager.GetString("Register1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;tab_box_2&quot; class=&quot;tab-box&quot;&gt;
        ///    &lt;div class=&quot;tab-box-content&quot;&gt;
        ///        &lt;div class=&quot;content-wrapper message-box&quot;&gt;
        ///            &lt;h2&gt;Регистрация на физическо лице с КЕП&lt;/h2&gt;
        ///            &lt;p&gt;Свържете Вашия четец за карти и картата с КЕП (или друг носител на КЕП, с който ще се регистрирате).&lt;/p&gt;
        ///            &lt;p&gt;Отворете &lt;a href=&quot;https://edelivery.egov.bg&quot;&gt;https://edelivery.egov.bg&lt;/a&gt;.&lt;/p&gt;
        ///            &lt;p&gt;Ще се зареди началният екран на уеб интерфейса.&lt;/p&gt;
        ///            &lt;p&gt;По подразбиране страницата пре [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Register2 {
            get {
                return ResourceManager.GetString("Register2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;tab_box_3&quot; class=&quot;tab-box&quot;&gt;
        ///    &lt;div class=&quot;tab-box-content&quot;&gt;
        ///        &lt;div class=&quot;content-wrapper message-box&quot;&gt;
        ///            &lt;h2&gt;Регистрация на физическо лице с ПИК на НАП&lt;/h2&gt;
        ///            &lt;p&gt;За да се регистрирате с персонален идентификационен код на Националната агенция по приходите (НАП) е необходимо да имате такъв. Ако нямате издаден, можете да се запознаете с процедурата на официалната интернет страница на &lt;a href=&quot;https://nra.bg/wps/portal/nra/uslugi/poluchavane-na-personalen-identifikacion [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Register3 {
            get {
                return ResourceManager.GetString("Register3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;tab_box_6&quot; class=&quot;tab-box&quot;&gt;
        ///    &lt;div class=&quot;tab-box-content&quot;&gt;
        ///        &lt;div class=&quot;content-wrapper message-box&quot;&gt;
        ///            &lt;h2&gt;Хранилище&lt;/h2&gt;
        ///            &lt;p&gt;В меню „Хранилище“, секция „Качени файлове“ всеки потребител може да добавя документи, които предстои да бъдат изпратени като прикачени файлове към съобщение. Документите се добавят чрез бутон „Качи файл“ (Фигура 6.1).&lt;/p&gt;
        ///            &lt;figure&gt;
        ///                &lt;img src=&quot;/Content/img/pixel.gif&quot; data-src=&quot;6_1.jpeg&quot; class=&quot;lazy&quot; alt=&quot;Фигура  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Storage {
            get {
                return ResourceManager.GetString("Storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изпращане и получаване на съобщение.
        /// </summary>
        public static string TitleMessages {
            get {
                return ResourceManager.GetString("TitleMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Администриране на профила.
        /// </summary>
        public static string TitleProfile {
            get {
                return ResourceManager.GetString("TitleProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация на физическо лице с ПИК на НОИ.
        /// </summary>
        public static string TitleRegister1 {
            get {
                return ResourceManager.GetString("TitleRegister1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация на физическо лице с КЕП.
        /// </summary>
        public static string TitleRegister2 {
            get {
                return ResourceManager.GetString("TitleRegister2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация на физическо лице с ПИК на НАП.
        /// </summary>
        public static string TitleRegister3 {
            get {
                return ResourceManager.GetString("TitleRegister3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хранилище.
        /// </summary>
        public static string TitleStorage {
            get {
                return ResourceManager.GetString("TitleStorage", resourceCulture);
            }
        }
    }
}
