//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDeliveryResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Landing {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Landing() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EDeliveryResources.Landing", typeof(Landing).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удостоверяване на време на изпращане на документи и съобщения от изпращача.
        /// </summary>
        public static string Advantages1 {
            get {
                return ResourceManager.GetString("Advantages1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удостоверяване на време на получаване на документи и съобщения от получателя.
        /// </summary>
        public static string Advantages2 {
            get {
                return ResourceManager.GetString("Advantages2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сигурност и защитеност на комуникацията.
        /// </summary>
        public static string Advantages3 {
            get {
                return ResourceManager.GetString("Advantages3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доказателствена тежест на комуникацията.
        /// </summary>
        public static string Advantages4 {
            get {
                return ResourceManager.GetString("Advantages4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гаранция за автентичност на обменените документи.
        /// </summary>
        public static string Advantages5 {
            get {
                return ResourceManager.GetString("Advantages5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Единен портал за достъп до електронни административни услуги.
        /// </summary>
        public static string BgGovLink1 {
            get {
                return ResourceManager.GetString("BgGovLink1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Електронна идентичност.
        /// </summary>
        public static string BgGovLink2 {
            get {
                return ResourceManager.GetString("BgGovLink2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Портал за обществени консултации.
        /// </summary>
        public static string BgGovLink3 {
            get {
                return ResourceManager.GetString("BgGovLink3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Портал за отворени данни на Република България.
        /// </summary>
        public static string BgGovLink4 {
            get {
                return ResourceManager.GetString("BgGovLink4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Система за електронно валидиране.
        /// </summary>
        public static string BgGovLink5 {
            get {
                return ResourceManager.GetString("BgGovLink5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помощен контактен център.
        /// </summary>
        public static string HelpDesk {
            get {
                return ResourceManager.GetString("HelpDesk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За информационни системи на Министерство на електронното управление:.
        /// </summary>
        public static string HelpDeskInfo {
            get {
                return ResourceManager.GetString("HelpDeskInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Избор на идентичност.
        /// </summary>
        public static string IdentityChoice {
            get {
                return ResourceManager.GetString("IdentityChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Физическо лице.
        /// </summary>
        public static string Individual {
            get {
                return ResourceManager.GetString("Individual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span&gt;ЗА&lt;/span&gt; БИЗНЕСА.
        /// </summary>
        public static string LandingForBusiness {
            get {
                return ResourceManager.GetString("LandingForBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span&gt;ЗА&lt;/span&gt; ГРАЖДАНИТЕ.
        /// </summary>
        public static string LandingForCitizans {
            get {
                return ResourceManager.GetString("LandingForCitizans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span&gt;ЗА&lt;/span&gt;&lt;br /&gt;СЛУЖИТЕЛИТЕ&lt;br /&gt;НА ДА.
        /// </summary>
        public static string LandingForDA {
            get {
                return ResourceManager.GetString("LandingForDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Република България.
        /// </summary>
        public static string LandingTitleRow1 {
            get {
                return ResourceManager.GetString("LandingTitleRow1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Министерство на електронното управление.
        /// </summary>
        public static string LandingTitleRow2 {
            get {
                return ResourceManager.GetString("LandingTitleRow2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Система за сигурно електронно връчване.
        /// </summary>
        public static string LandingTitleRow3 {
            get {
                return ResourceManager.GetString("LandingTitleRow3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Юридическо лице.
        /// </summary>
        public static string LegalEntity {
            get {
                return ResourceManager.GetString("LegalEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помощен контактен център.
        /// </summary>
        public static string LinkContactCenter {
            get {
                return ResourceManager.GetString("LinkContactCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to От 17.01.2022 г. функционира надградената Система за сигурно електронно връчване. При проблеми и затруднения, отнасящи се до новоизградените функционалности, може да сигнализирате на &lt;a href=&quot;mailto:Help@e-gov.bg&quot;&gt;Help@e-gov.bg&lt;/a&gt;, като за по-голяма оперативност e необходимо да предоставите Ваш (мобилен) телефон..
        /// </summary>
        public static string Message1 {
            get {
                return ResourceManager.GetString("Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Считано от 24.03.2022 г. се въвежда максимален общ размер от 1 GB за всеки профил в секция &quot;Качени файлове&quot; в меню &quot;Хранилище&quot; на ССЕВ. Максималният размер на единичен файл, качен самостоятелно в Хранилището и прикачен към съобщение, е до 255 MB..
        /// </summary>
        public static string Message2 {
            get {
                return ResourceManager.GetString("Message2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Съобщение:.
        /// </summary>
        public static string MessageTitle {
            get {
                return ResourceManager.GetString("MessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Администрация.
        /// </summary>
        public static string PublicAdministration {
            get {
                return ResourceManager.GetString("PublicAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Брой регистрирани администрации:.
        /// </summary>
        public static string RegisteredAdministrations {
            get {
                return ResourceManager.GetString("RegisteredAdministrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Брой регистрирани други ЮЛ:.
        /// </summary>
        public static string RegisteredLegals {
            get {
                return ResourceManager.GetString("RegisteredLegals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Брой регистрирани лица по чл. 1, ал. 2 ЗЕУ:.
        /// </summary>
        public static string RegisteredSocialOrganisations {
            get {
                return ResourceManager.GetString("RegisteredSocialOrganisations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пълен списък на регистрираните е наличен {0} тук {1}.
        /// </summary>
        public static string RegistrationsFullLink {
            get {
                return ResourceManager.GetString("RegistrationsFullLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В случай, че нямате регистрация, регистрирайте се. За регистрация ви е необходим квалифициран електронен подпис или електронна идентичност..
        /// </summary>
        public static string Step1 {
            get {
                return ResourceManager.GetString("Step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За юридически лица - след регистрацията изчакайте одобрение от администраторите на системата..
        /// </summary>
        public static string Step2 {
            get {
                return ResourceManager.GetString("Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Влезте в Системата за сигурно електронно връчване и изпратете или получете съобщение или документи..
        /// </summary>
        public static string Step3 {
            get {
                return ResourceManager.GetString("Step3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предимства.
        /// </summary>
        public static string TitleAdvantages {
            get {
                return ResourceManager.GetString("TitleAdvantages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Как се използва?.
        /// </summary>
        public static string TitleHowToUse {
            get {
                return ResourceManager.GetString("TitleHowToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полезни връзки.
        /// </summary>
        public static string TitlePartOfBgGov {
            get {
                return ResourceManager.GetString("TitlePartOfBgGov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрирани участници.
        /// </summary>
        public static string TitleRegisteredUsers {
            get {
                return ResourceManager.GetString("TitleRegisteredUsers", resourceCulture);
            }
        }
    }
}
