//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDeliveryResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LoginRegisterPage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoginRegisterPage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EDeliveryResources.LoginRegisterPage", typeof(LoginRegisterPage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вече сте потребител на системата?.
        /// </summary>
        public static string AreYouAUser {
            get {
                return ResourceManager.GetString("AreYouAUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профилът на Юридическо лице може да се достъпва от едно или повече физически лица, на които е даден достъп. За регистрацията на Юридическо лице е нужно да имате вече създаден профил като физическо лице. След това трябва да попълните и подишете с персонален ектронен подпис формуляра за регистрация. След създаване на регистрацията, моля изчакайте да бъдете информирани за нейната активация!.
        /// </summary>
        public static string DescriptionRegisterLegal {
            get {
                return ResourceManager.GetString("DescriptionRegisterLegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уведомяваме Ви, че във връзка с надграждане функционалностите на системата за сигурно електронно връчване, към настоящия момент заявления за присъединяване към системата за сигурно електронно връчване на юридически лица, могат да се подават само от лице представляващо дружеството (управител, прокурист, представляващ и др.). С цел осигуряване на сигурност на профила и на цялостния процес по заявяване и получаване на електронни административни услуги и връчване на административни актове, към настоящия момент  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DescriptionRegisterLegalAddOn {
            get {
                return ResourceManager.GetString("DescriptionRegisterLegalAddOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Като Физическо лице ще имате достъп до личните си получени и изпратени съобщения, както и да управлявате своя профил..
        /// </summary>
        public static string DescriptionRegisterPerson {
            get {
                return ResourceManager.GetString("DescriptionRegisterPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заявление за присъединяване на юридическо лице.
        /// </summary>
        public static string DownloadRegistrationForm {
            get {
                return ResourceManager.GetString("DownloadRegistrationForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Грешка! Входът с потребителско име и парола е забранен! Моля използвайте друг метод на автентикация!.
        /// </summary>
        public static string ErrorLoginUserPassDisabled {
            get {
                return ResourceManager.GetString("ErrorLoginUserPassDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За повече информация {0}виж на страницата на Изпълнителна агенция &quot;Инфраструктура на елетронното управление&quot;{1}.
        /// </summary>
        public static string ForMoreInformation {
            get {
                return ResourceManager.GetString("ForMoreInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успешно се регистрирахте в системата за сигурно електронно връчване!.
        /// </summary>
        public static string HeadingRegistrationSuccess {
            get {
                return ResourceManager.GetString("HeadingRegistrationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес.
        /// </summary>
        public static string LabelAddress {
            get {
                return ResourceManager.GetString("LabelAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата на раждане.
        /// </summary>
        public static string LabelBirthDate {
            get {
                return ResourceManager.GetString("LabelBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Форма за регистрация.
        /// </summary>
        public static string LabelChoosePDF {
            get {
                return ResourceManager.GetString("LabelChoosePDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Град.
        /// </summary>
        public static string LabelCity {
            get {
                return ResourceManager.GetString("LabelCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потвърдете паролата.
        /// </summary>
        public static string LabelConfirmPassword {
            get {
                return ResourceManager.GetString("LabelConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Държава.
        /// </summary>
        public static string LabelCountry {
            get {
                return ResourceManager.GetString("LabelCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЕГН.
        /// </summary>
        public static string LabelEGN {
            get {
                return ResourceManager.GetString("LabelEGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail адрес.
        /// </summary>
        public static string LabelEmailAddress {
            get {
                return ResourceManager.GetString("LabelEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Желая да получавам нотификация по е-mail.
        /// </summary>
        public static string LabelEmailNotifications {
            get {
                return ResourceManager.GetString("LabelEmailNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Желая да получавам нотификация по е-mail при отваряне на съобщение.
        /// </summary>
        public static string LabelEmailNotificationsOnDelivery {
            get {
                return ResourceManager.GetString("LabelEmailNotificationsOnDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Желая да получавам нотификация по е-mail при получаване на ново съобщение.
        /// </summary>
        public static string LabelEmailNotificationsOnReceiving {
            get {
                return ResourceManager.GetString("LabelEmailNotificationsOnReceiving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име.
        /// </summary>
        public static string LabelFirstName {
            get {
                return ResourceManager.GetString("LabelFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string LabelLastName {
            get {
                return ResourceManager.GetString("LabelLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приемам &lt;a href=&quot;{0}&quot; target=&quot;_blank&quot;&gt;условията за ползване&lt;/a&gt; на услугата.
        /// </summary>
        public static string LabelLicenceAgreement {
            get {
                return ResourceManager.GetString("LabelLicenceAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Презиме.
        /// </summary>
        public static string LabelMiddleName {
            get {
                return ResourceManager.GetString("LabelMiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Парола.
        /// </summary>
        public static string LabelPassword {
            get {
                return ResourceManager.GetString("LabelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЕГН/ЛНЧ.
        /// </summary>
        public static string LabelPersonalIdentifier {
            get {
                return ResourceManager.GetString("LabelPersonalIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Желая да получавам нотификация по SMS.
        /// </summary>
        public static string LabelPhoneNotifications {
            get {
                return ResourceManager.GetString("LabelPhoneNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Желая да получавам нотификация по SMS при получаване на ново съобщение.
        /// </summary>
        public static string LabelPhoneNotificationsOnReceiving {
            get {
                return ResourceManager.GetString("LabelPhoneNotificationsOnReceiving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        public static string LabelPhoneNumber {
            get {
                return ResourceManager.GetString("LabelPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Област.
        /// </summary>
        public static string LabelState {
            get {
                return ResourceManager.GetString("LabelState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребителско име.
        /// </summary>
        public static string LabelUserName {
            get {
                return ResourceManager.GetString("LabelUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Желая да получавам нотификация по Viber.
        /// </summary>
        public static string LabelViberNotifications {
            get {
                return ResourceManager.GetString("LabelViberNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Желая да получавам нотификация по Viber при отваряне на съобщение.
        /// </summary>
        public static string LabelViberNotificationsOnDelivery {
            get {
                return ResourceManager.GetString("LabelViberNotificationsOnDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Желая да получавам нотификация по Viber при получаване на ново съобщение.
        /// </summary>
        public static string LabelViberNotificationsOnReceiving {
            get {
                return ResourceManager.GetString("LabelViberNotificationsOnReceiving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход в системата.
        /// </summary>
        public static string LinkLogin {
            get {
                return ResourceManager.GetString("LinkLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забравена парола.
        /// </summary>
        public static string LinkLostPassword {
            get {
                return ResourceManager.GetString("LinkLostPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля, уверете се, че устройството с електронния Ви подпис е поставено в компютъра. Ако не е поставено, поставете го и тогава продължете..
        /// </summary>
        public static string LoginAuthCertificateNote {
            get {
                return ResourceManager.GetString("LoginAuthCertificateNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При електронна автентикация с квалифициран електронен подпис е необходимо същия да съдържа информация за ЕГН на автора на подписа в полето serial number = ЕГН. В съответствие § 1, т. 22 от допълнителните разпоредби на Закона за електронното управление при условията на § 5 от Наредбата за общите изисквания към инф. системи, регистрите и електронните адм. услуги..
        /// </summary>
        public static string LoginKepNotice {
            get {
                return ResourceManager.GetString("LoginKepNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход с Квалифициран Електронен Подпис.
        /// </summary>
        public static string LoginWithKep {
            get {
                return ResourceManager.GetString("LoginWithKep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За регистрация на юридическо лице е необходимо физическото лице - заявител да е регистрирано в системата за Сигурно Електронно Връчване и да влезе в профила си!.
        /// </summary>
        public static string MessageLoginToRegisterLegalPerson {
            get {
                return ResourceManager.GetString("MessageLoginToRegisterLegalPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стартира се процес по електронна автентикация.
        /// </summary>
        public static string MessageStartingCertificateAuth {
            get {
                return ResourceManager.GetString("MessageStartingCertificateAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имена на латиница.
        /// </summary>
        public static string NamesInLatin {
            get {
                return ResourceManager.GetString("NamesInLatin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За регистрация на физическо лице, моля излезте от профила си!.
        /// </summary>
        public static string TextAuthentictedRegisterPerson {
            get {
                return ResourceManager.GetString("TextAuthentictedRegisterPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля, изберете начин за удостоверяване на Вашата самоличност при регистрация в системата за сигурно електронно връчване..
        /// </summary>
        public static string TextChooseRegisterType {
            get {
                return ResourceManager.GetString("TextChooseRegisterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо е да валидирате своята идентичност посредством EID. Моля, свръжете картовия четец, поставете Вашата карта за Електронна Идентичност в него и натиснете бутона &quot;Регистрация&quot;.
        ///За повече информация относно използватене на карта за Електронна Идентичност, моля посетете линка по-долу..
        /// </summary>
        public static string TextInformationEID {
            get {
                return ResourceManager.GetString("TextInformationEID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За да регистирате профил на юридическо лице е нужно да имате регистрация като физическо такова. &lt;br/&gt;Моля попълнете потребителското име и паролата на своя профил:.
        /// </summary>
        public static string TextLegalRepresentative {
            get {
                return ResourceManager.GetString("TextLegalRepresentative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вече сте потребител на системата? Можете да започнете да я използвате, като влезете на страницата за ВХОД..
        /// </summary>
        public static string TextLogin {
            get {
                return ResourceManager.GetString("TextLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все още нямате регистрация? Можете да се регистрирате като физическо или юридическо лице и да се възползвате от удобството на електронното доставяне на документ..
        /// </summary>
        public static string TextRegister {
            get {
                return ResourceManager.GetString("TextRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За да направите регистрация чрез електронен подпис е необходимо да свалите електронния формуляр &quot;Заявление за регистрация в системата за сигурно електронно връчване - Юридическо лице&quot;, да попълните данните на юридическо лице и да го подпишете с Електронен подпис. 
        ///Завършете регистрацията като качите обратно попълнения и подписан формуляр във формата по-долу и попълните останалите полета..
        /// </summary>
        public static string TextRegistrationInstructionsLegal {
            get {
                return ResourceManager.GetString("TextRegistrationInstructionsLegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За да направите регистрация чрез електронен подпис е необходимо да свалите електронния формуляр &quot;Заявление за регистрация в системата за сигурно електронно връчване&quot;, да попълните личните си данни и да го подпишете с Вашия електронен подпис. 
        ///Завършете регистрацията си като качите обратно попълнения и подписан формуляр във формата по-долу и попълните останалите полета..
        /// </summary>
        public static string TextRegistrationInstructionsPerson {
            get {
                return ResourceManager.GetString("TextRegistrationInstructionsPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вашата регистрация приключи успешно! Администратор на системата ще провери и активира Вашата регистрация. Ще получите нотификация на посочения от вас e-mail адрес и/или телефонен номер, когато можете да започнете да използвате системата..
        /// </summary>
        public static string TextRegistrationSuccess {
            get {
                return ResourceManager.GetString("TextRegistrationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Декларирам, че информацията, посочена в тази форма, е вярна и точна. Известно ми е, че за умишлено попълване на неверни данни нося отговорност по чл. 313 НК..
        /// </summary>
        public static string TextValidDataResponsibility {
            get {
                return ResourceManager.GetString("TextValidDataResponsibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неуспешен вход в системата с КЕП!.
        /// </summary>
        public static string TitleKepAuthFailed {
            get {
                return ResourceManager.GetString("TitleKepAuthFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход с потребител и парола.
        /// </summary>
        public static string TitleLoginCredentials {
            get {
                return ResourceManager.GetString("TitleLoginCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string TitleLoginKEP {
            get {
                return ResourceManager.GetString("TitleLoginKEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация Юридическо лице.
        /// </summary>
        public static string TitleRegisterLegal {
            get {
                return ResourceManager.GetString("TitleRegisterLegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация Физическо лице.
        /// </summary>
        public static string TitleRegisterPerson {
            get {
                return ResourceManager.GetString("TitleRegisterPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация на администрация.
        /// </summary>
        public static string TitleRegisterPublicAdministration {
            get {
                return ResourceManager.GetString("TitleRegisterPublicAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заявление за присъединяване на лица по чл. 1, ал. 1 и ал. 2 от Закона за електронно управление.
        /// </summary>
        public static string TitleRegisterPublicAdministrationApplication1 {
            get {
                return ResourceManager.GetString("TitleRegisterPublicAdministrationApplication1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заявление за присъединяване към Системата за сигурно електронно връчване на структура/и на административен орган по чл. 1, ал. 1 от Закона за електронното управление .
        /// </summary>
        public static string TitleRegisterPublicAdministrationApplication2 {
            get {
                return ResourceManager.GetString("TitleRegisterPublicAdministrationApplication2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Представител на Юридическото лице.
        /// </summary>
        public static string TitleSectinLegalRepresentative {
            get {
                return ResourceManager.GetString("TitleSectinLegalRepresentative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес.
        /// </summary>
        public static string TitleSectionAddress {
            get {
                return ResourceManager.GetString("TitleSectionAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данни от eID.
        /// </summary>
        public static string TitleSectionEIDData {
            get {
                return ResourceManager.GetString("TitleSectionEIDData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данни от КЕП.
        /// </summary>
        public static string TitleSectionKEPData {
            get {
                return ResourceManager.GetString("TitleSectionKEPData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лични данни.
        /// </summary>
        public static string TitleSectionPersonalData {
            get {
                return ResourceManager.GetString("TitleSectionPersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данни от автентикиращия орган.
        /// </summary>
        public static string TitleSectionPIKData {
            get {
                return ResourceManager.GetString("TitleSectionPIKData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данни за профила.
        /// </summary>
        public static string TitleSectionProfileData {
            get {
                return ResourceManager.GetString("TitleSectionProfileData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инструкция за регистрация.
        /// </summary>
        public static string TitleSectionRegistrationInstructions {
            get {
                return ResourceManager.GetString("TitleSectionRegistrationInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заявление за прекратяване присъединяването към Системата за сигурно електронно връчване.
        /// </summary>
        public static string TitleUnregisterPublicAdministrationApplication {
            get {
                return ResourceManager.GetString("TitleUnregisterPublicAdministrationApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Можете да започнете да я използвате..
        /// </summary>
        public static string YouCanUseIt {
            get {
                return ResourceManager.GetString("YouCanUseIt", resourceCulture);
            }
        }
    }
}
