//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDeliveryResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NotificationsAndHelp {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotificationsAndHelp() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EDeliveryResources.NotificationsAndHelp", typeof(NotificationsAndHelp).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрацията за {0} е потвърдена от {1}, мейл {2}.
        ///Това съобщение e изпратено от Система за сигурно електронно връчване, като част от процеса на регистрация и не е необходимо да отговаряте!.
        /// </summary>
        public static string EDelliveryAutoMessageInstitutionRegistrationBody {
            get {
                return ResourceManager.GetString("EDelliveryAutoMessageInstitutionRegistrationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрацията е потвърдена за {0}.
        /// </summary>
        public static string EDelliveryAutoMessageInstitutionRegistrationSubject {
            get {
                return ResourceManager.GetString("EDelliveryAutoMessageInstitutionRegistrationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здравейте &lt;login&gt;,
        ///
        ///Регистрираният от вас профил &lt;profile&gt; в системата за сигурно електронно връчване беше успешно активиран. Можете да започнете да използвате профила си като се логнете в систамата на адрес &lt;url&gt; 
        ///
        ///
        ///Това съобщение e изпратено от Система за сигурно електронно връчване, която се изгражда и поддържа от Държавна агенция „Електронно управление“ по силата на чл. 26 от Закона за електронно управление. Информацията в съобщението е предназначена само за получателя/ите. Всяко неоторизирано изпо [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NotificationActivatedEmailBody {
            get {
                return ResourceManager.GetString("NotificationActivatedEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Държавна агенция „Електронно управление“, Система  за сигурно електронно връчване - Профил &lt;profile&gt; е акивиран!.
        /// </summary>
        public static string NotificationActivatedEmailSubject {
            get {
                return ResourceManager.GetString("NotificationActivatedEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://edelivery.egov.bg : Profil &lt;profile&gt; e uspeshno aktiviran!.
        /// </summary>
        public static string NotificationActivatedSMSSubject {
            get {
                return ResourceManager.GetString("NotificationActivatedSMSSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здравейте &lt;login&gt;,
        ///
        ///Изпратено през профил &lt;sender&gt; съобщение &quot;&lt;messagesubject&gt;&quot; е отворено от &lt;profile&gt;. Можете да проверите детайли за отварянето, като  влезете в профила си на адрес &lt;url&gt;.
        ///
        ///Това съобщение e изпратено от Система за сигурно електронно връчване, която се изгражда и поддържа от Държавна агенция „Електронно управление“ по силата на чл. 26 от Закона за електронно управление. Информацията в съобщението е предназначена само за получателя/ите. Всяко неоторизирано използване или разпространяван [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NotificationDeliveredEmailBody {
            get {
                return ResourceManager.GetString("NotificationDeliveredEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Държавна агенция „Електронно управление“, Система  за сигурно електронно връчване – Отворено съобщение!.
        /// </summary>
        public static string NotificationDeliveredEmailSubject {
            get {
                return ResourceManager.GetString("NotificationDeliveredEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здравейте,
        ///
        ///Имате ново връчено съобщение/документи от &lt;sender&gt;. За да го получите е необходимо да отворите линк &lt;url&gt; Ако нямате регистрация, необходимо е да си направите такава
        ///
        ///
        ///Това съобщение e изпратено от Система за сигурно електронно връчване, която се изгражда и поддържа от Държавна агенция „Електронно управление“ по силата на чл. 26 от Закона за електронно управление. Информацията в съобщението е предназначена само за получателя/ите. Всяко неоторизирано използване или разпространяване на това с [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NotificationReceivedAndRegisterEmailBody {
            get {
                return ResourceManager.GetString("NotificationReceivedAndRegisterEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Държавна агенция „Електронно управление“, Система  за сигурно електронно връчване – Ново получено съобщение!.
        /// </summary>
        public static string NotificationReceivedAndRegisterEmailSubject {
            get {
                return ResourceManager.GetString("NotificationReceivedAndRegisterEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ima novo vrycheno syobstenie za  &lt;profile&gt;. Registriraite se na adres &lt;url&gt;, za da go poluchite..
        /// </summary>
        public static string NotificationReceivedAndRegisterSMSBody {
            get {
                return ResourceManager.GetString("NotificationReceivedAndRegisterSMSBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здравейте &lt;login&gt;,
        ///
        ///Току-що на профил &lt;profile&gt; бе връчено ново съобщение/документи от &lt;sender&gt;. Можете да го получите като  като влезете в профила си на адрес &lt;url&gt;.
        ///
        ///Това съобщение e изпратено от Система за сигурно електронно връчване, която се изгражда и поддържа от Държавна агенция „Електронно управление“ по силата на чл. 26 от Закона за електронно управление. Информацията в съобщението е предназначена само за получателя/ите. Всяко неоторизирано използване или разпространяване на това съобщение или  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NotificationReceivedEmailBody {
            get {
                return ResourceManager.GetString("NotificationReceivedEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Държавна агенция „Електронно управление“, Система  за сигурно електронно връчване – Ново получено съобщение!.
        /// </summary>
        public static string NotificationReceivedEmailSubject {
            get {
                return ResourceManager.GetString("NotificationReceivedEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://edelivery.egov.bg : Ima novo vrycheno syobstenie za  &lt;profile&gt; ot &lt;sender&gt;..
        /// </summary>
        public static string NotificationReceivedSMSBody {
            get {
                return ResourceManager.GetString("NotificationReceivedSMSBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здравейте &lt;profile&gt;,
        ///
        ///Току-що на &lt;profile&gt; бе връчено ново съобщение/документи от &lt;sender&gt;. 
        ///Можете да го получите като влезете на адрес &lt;url&gt; и въведете код за достъп: &lt;accesscode&gt;
        ///
        ///Това съобщение e изпратено от Система за сигурно електронно връчване, която се изгражда и поддържа от Държавна агенция „Електронно управление“ по силата на чл. 26 от Закона за електронно управление. Информацията в съобщението е предназначена само за получателя/ите притежаващи код за достъп до съобщението. Всяко неоторизира [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NotificationReceivedWithCodeEmailBody {
            get {
                return ResourceManager.GetString("NotificationReceivedWithCodeEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Държавна агенция „Електронно управление“, Система  за сигурно електронно връчване – съобщение с код за достъп!.
        /// </summary>
        public static string NotificationReceivedWithCodeEmailSubject {
            get {
                return ResourceManager.GetString("NotificationReceivedWithCodeEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;url&gt;
        ///KOD ZA DOSTAP:&lt;accesscode&gt;
        ///Imate saobshtenie ot &lt;sender&gt;..
        /// </summary>
        public static string NotificationReceivedWithCodeSMSBody {
            get {
                return ResourceManager.GetString("NotificationReceivedWithCodeSMSBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здравейте &lt;login&gt;,
        ///
        ///Регистрираният от Вас профил &lt;profile&gt; в системата за сигурно електронно връчване е закрит от администратор на системата.  За повече информация, моля свържете се с администрацията на Системата за сигурно електронно връчване.
        ///
        ///
        ///Това съобщение e изпратено от Система за сигурно електронно връчване, която се изгражда и поддържа от Държавна агенция „Електронно управление“ по силата на чл. 26 от Закона за електронно управление. Информацията в съобщението е предназначена само за получателя [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NotificationRejectedEmailBody {
            get {
                return ResourceManager.GetString("NotificationRejectedEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Държавна агенция „Електронно управление“, Система за сигурно електронно връчване - Профил &lt;profile&gt; е закрит!.
        /// </summary>
        public static string NotificationRejectedEmailSubject {
            get {
                return ResourceManager.GetString("NotificationRejectedEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://edelivery.egov.bg : Profil &lt;profile&gt; e zakrit ot administrator na sistemata! Svyrjete se s administratora na sistemata za poveche informaciq..
        /// </summary>
        public static string NotificationRejectedSMSBody {
            get {
                return ResourceManager.GetString("NotificationRejectedSMSBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здравейте,
        ///
        ///Имате ново връчено съобщение/документи от &lt;sender&gt;. За да го получите е необходимо да отворите линк &lt;url&gt; Ако нямате регистрация, необходимо е да си направите такава
        ///
        ///
        ///Това съобщение e изпратено от Система за сигурно електронно връчване, която се изгражда и поддържа от Държавна агенция „Електронно управление“ по силата на чл. 26 от Закона за електронно управление. Информацията в съобщението е предназначена само за получателя/ите. Всяко неоторизирано използване или разпространяване на това с [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NotificationSentAndRegisterEmailBody {
            get {
                return ResourceManager.GetString("NotificationSentAndRegisterEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Държавна агенция „Електронно управление“, Система  за сигурно електронно връчване – Ново получено съобщение!.
        /// </summary>
        public static string NotificationSentAndRegisterEmailSubject {
            get {
                return ResourceManager.GetString("NotificationSentAndRegisterEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ima novo vrycheno syobstenie za  &lt;profile&gt;. Registriraite se na adres &lt;url&gt;, za da go poluchite..
        /// </summary>
        public static string NotificationSentAndRegisterSMSBody {
            get {
                return ResourceManager.GetString("NotificationSentAndRegisterSMSBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия на сайта: .
        /// </summary>
        public static string SiteVersion {
            get {
                return ResourceManager.GetString("SiteVersion", resourceCulture);
            }
        }
    }
}
