//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDeliveryResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProfilePage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProfilePage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EDeliveryResources.ProfilePage", typeof(ProfilePage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добави още.
        /// </summary>
        public static string ButtonAddMoreDos {
            get {
                return ResourceManager.GetString("ButtonAddMoreDos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добави.
        /// </summary>
        public static string ButtonAddReceiver {
            get {
                return ResourceManager.GetString("ButtonAddReceiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прикачи.
        /// </summary>
        public static string ButtonAttach {
            get {
                return ResourceManager.GetString("ButtonAttach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изчисти филтрите.
        /// </summary>
        public static string ButtonClear {
            get {
                return ResourceManager.GetString("ButtonClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потвърди.
        /// </summary>
        public static string ButtonConfirmAccessCode {
            get {
                return ResourceManager.GetString("ButtonConfirmAccessCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заяви превод.
        /// </summary>
        public static string ButtonCreateTranslation {
            get {
                return ResourceManager.GetString("ButtonCreateTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Препрати.
        /// </summary>
        public static string ButtonForwardMessage {
            get {
                return ResourceManager.GetString("ButtonForwardMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добави.
        /// </summary>
        public static string ButtonGrantAccess {
            get {
                return ResourceManager.GetString("ButtonGrantAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Синхронизация на имена.
        /// </summary>
        public static string ButtonGRAONamesSync {
            get {
                return ResourceManager.GetString("ButtonGRAONamesSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подай заявление за промяна на данни.
        /// </summary>
        public static string ButtonRequestProfileChange {
            get {
                return ResourceManager.GetString("ButtonRequestProfileChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запази.
        /// </summary>
        public static string ButtonSaveMessage {
            get {
                return ResourceManager.GetString("ButtonSaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Търси.
        /// </summary>
        public static string ButtonSearch {
            get {
                return ResourceManager.GetString("ButtonSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изпрати.
        /// </summary>
        public static string ButtonSendMessage {
            get {
                return ResourceManager.GetString("ButtonSendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детайли за препращането.
        /// </summary>
        public static string ForwardedHistoryLink {
            get {
                return ResourceManager.GetString("ForwardedHistoryLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Препратено съобщение.
        /// </summary>
        public static string ForwardedMessage {
            get {
                return ResourceManager.GetString("ForwardedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Достъп до профила.
        /// </summary>
        public static string HistoryActionAccessProfile {
            get {
                return ResourceManager.GetString("HistoryActionAccessProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профилът е активират от предишен пасивен статус.
        /// </summary>
        public static string HistoryActionBringProfileInForce {
            get {
                return ResourceManager.GetString("HistoryActionBringProfileInForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профилът е създаден.
        /// </summary>
        public static string HistoryActionCreateProfile {
            get {
                return ResourceManager.GetString("HistoryActionCreateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профилът е създаден от {0}..
        /// </summary>
        public static string HistoryActionDetailsCreateProfile {
            get {
                return ResourceManager.GetString("HistoryActionDetailsCreateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Даден е достъп до профила на {0}..
        /// </summary>
        public static string HistoryActionDetailsGrantAccessToProfile {
            get {
                return ResourceManager.GetString("HistoryActionDetailsGrantAccessToProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aктивиран е профил {0}..
        /// </summary>
        public static string HistoryActionDetailsProfileActivated {
            get {
                return ResourceManager.GetString("HistoryActionDetailsProfileActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Следните данни са актуализирани: {0}.
        /// </summary>
        public static string HistoryActionDetailsProfileUpdated {
            get {
                return ResourceManager.GetString("HistoryActionDetailsProfileUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отнет е достъпът до профила на {0}..
        /// </summary>
        public static string HistoryActionDetailsRemoveAccessToProfile {
            get {
                return ResourceManager.GetString("HistoryActionDetailsRemoveAccessToProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Даден е достъп до профила.
        /// </summary>
        public static string HistoryActionGrantAccessToProfile {
            get {
                return ResourceManager.GetString("HistoryActionGrantAccessToProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профилът е с премахнат статус &quot;само за четене&quot;.
        /// </summary>
        public static string HistoryActionMarkAsNonReadonly {
            get {
                return ResourceManager.GetString("HistoryActionMarkAsNonReadonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профилът е със статус &quot;само за четене&quot;.
        /// </summary>
        public static string HistoryActionMarkAsReadonly {
            get {
                return ResourceManager.GetString("HistoryActionMarkAsReadonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профилът е акивиран.
        /// </summary>
        public static string HistoryActionProfileActivated {
            get {
                return ResourceManager.GetString("HistoryActionProfileActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профилът е деактивиран.
        /// </summary>
        public static string HistoryActionProfileDeactivated {
            get {
                return ResourceManager.GetString("HistoryActionProfileDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профилът е актуализиран.
        /// </summary>
        public static string HistoryActionProfileUpdated {
            get {
                return ResourceManager.GetString("HistoryActionProfileUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отнет достъп до профила.
        /// </summary>
        public static string HistoryActionRemoveAccessToProfile {
            get {
                return ResourceManager.GetString("HistoryActionRemoveAccessToProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действие.
        /// </summary>
        public static string HistoryTableAction {
            get {
                return ResourceManager.GetString("HistoryTableAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Извършено от.
        /// </summary>
        public static string HistoryTableActor {
            get {
                return ResourceManager.GetString("HistoryTableActor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        public static string HistoryTableDate {
            get {
                return ResourceManager.GetString("HistoryTableDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детайли.
        /// </summary>
        public static string HistoryTableDetails {
            get {
                return ResourceManager.GetString("HistoryTableDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP адрес.
        /// </summary>
        public static string HistoryTableIP {
            get {
                return ResourceManager.GetString("HistoryTableIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уважаеми потребители,&lt;br/&gt;ако желаете да получавате съобщения по е-майл, моля маркирайте горните радиобутони.&lt;br/&gt;
        ///В случай, че имате предпочитания към един от каналите за нотификация: Viber или SMS, избирате само един: или Viber или SMS.&lt;br/&gt;
        ///Ако не желаете да получавате съобщения, не избирате нито един канал.&lt;br/&gt;
        ///За да получавате съобщения по Viber e необходимо приложението да бъде инсталирано на мобилното Ви устройство и да имате активен Viber профил..
        /// </summary>
        public static string InfoPhoneNotificationChoice {
            get {
                return ResourceManager.GetString("InfoPhoneNotificationChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поради необходимост от оптимизиране работата на системата, след &lt;strong&gt;25.05.2020 г.&lt;/strong&gt; нотификациите към  административни органи ще се изпращат само по имейл адреса, вписан в профила..
        /// </summary>
        public static string InfoPhoneNotificationsTurnedOff {
            get {
                return ResourceManager.GetString("InfoPhoneNotificationsTurnedOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код за достъп.
        /// </summary>
        public static string LabelAccessCode {
            get {
                return ResourceManager.GetString("LabelAccessCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Път до документа.
        /// </summary>
        public static string LabelAttachedDocument {
            get {
                return ResourceManager.GetString("LabelAttachedDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование.
        /// </summary>
        public static string LabelAttachedDocumentName {
            get {
                return ResourceManager.GetString("LabelAttachedDocumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Път до документа.
        /// </summary>
        public static string LabelChooseDocument {
            get {
                return ResourceManager.GetString("LabelChooseDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текуща парола:.
        /// </summary>
        public static string LabelCurrentPassword {
            get {
                return ResourceManager.GetString("LabelCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Входящ номер.
        /// </summary>
        public static string LabelDocumentRegNumber {
            get {
                return ResourceManager.GetString("LabelDocumentRegNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Документи за връчване.
        /// </summary>
        public static string LabelDocuments {
            get {
                return ResourceManager.GetString("LabelDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email адрес.
        /// </summary>
        public static string LabelEmail {
            get {
                return ResourceManager.GetString("LabelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въведете код за достъп.
        /// </summary>
        public static string LabelEnterAccessCode {
            get {
                return ResourceManager.GetString("LabelEnterAccessCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главен орган.
        /// </summary>
        public static string LabelHeadInstName {
            get {
                return ResourceManager.GetString("LabelHeadInstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЕИК.
        /// </summary>
        public static string LabelInstEIK {
            get {
                return ResourceManager.GetString("LabelInstEIK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование.
        /// </summary>
        public static string LabelInstName {
            get {
                return ResourceManager.GetString("LabelInstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата на влизане в сила.
        /// </summary>
        public static string LabelLegalInForce {
            get {
                return ResourceManager.GetString("LabelLegalInForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име.
        /// </summary>
        public static string LabelLegalName {
            get {
                return ResourceManager.GetString("LabelLegalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата на излизане от сила.
        /// </summary>
        public static string LabelLegalOutForce {
            get {
                return ResourceManager.GetString("LabelLegalOutForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистриран от.
        /// </summary>
        public static string LabelLegalRegisteredBy {
            get {
                return ResourceManager.GetString("LabelLegalRegisteredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЕИК.
        /// </summary>
        public static string LabelLegalRegNum {
            get {
                return ResourceManager.GetString("LabelLegalRegNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Връчено:.
        /// </summary>
        public static string LabelMessageReceivedOn {
            get {
                return ResourceManager.GetString("LabelMessageReceivedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получател.
        /// </summary>
        public static string LabelMessageReceiver {
            get {
                return ResourceManager.GetString("LabelMessageReceiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЕГН/ЛНЧ.
        /// </summary>
        public static string LabelMessageReceiverPersonalIdentifier {
            get {
                return ResourceManager.GetString("LabelMessageReceiverPersonalIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Връчител.
        /// </summary>
        public static string LabelMessageSender {
            get {
                return ResourceManager.GetString("LabelMessageSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подадено:.
        /// </summary>
        public static string LabelMessageSentOn {
            get {
                return ResourceManager.GetString("LabelMessageSentOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        public static string LabelMessageStatus {
            get {
                return ResourceManager.GetString("LabelMessageStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Съдържание.
        /// </summary>
        public static string LabelMessageText {
            get {
                return ResourceManager.GetString("LabelMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (до 100 000 символа).
        /// </summary>
        public static string LabelMessageTextMaxLength {
            get {
                return ResourceManager.GetString("LabelMessageTextMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заглавие.
        /// </summary>
        public static string LabelMessageTitle {
            get {
                return ResourceManager.GetString("LabelMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mоето пространство.
        /// </summary>
        public static string LabelMySpace {
            get {
                return ResourceManager.GetString("LabelMySpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нова парола:.
        /// </summary>
        public static string LabelNewPassword {
            get {
                return ResourceManager.GetString("LabelNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потвърди нова парола:.
        /// </summary>
        public static string LabelNewPasswordAgain {
            get {
                return ResourceManager.GetString("LabelNewPasswordAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не са намерени съобщения, отговарящи на критерия за търсене!.
        /// </summary>
        public static string LabelNoMessagesFromSearch {
            get {
                return ResourceManager.GetString("LabelNoMessagesFromSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Няма заявени преводи към съобщението..
        /// </summary>
        public static string LabelNoMessageTranslations {
            get {
                return ResourceManager.GetString("LabelNoMessageTranslations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все още няма получени съобщения..
        /// </summary>
        public static string LabelNoReceivedMessages {
            get {
                return ResourceManager.GetString("LabelNoReceivedMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все още няма изпратени съобщения.
        /// </summary>
        public static string LabelNoSentMessages {
            get {
                return ResourceManager.GetString("LabelNoSentMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЕГН/ЛНЧ.
        /// </summary>
        public static string LabelPersonalIdentifier {
            get {
                return ResourceManager.GetString("LabelPersonalIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата на раждане.
        /// </summary>
        public static string LabelPersonBirthDay {
            get {
                return ResourceManager.GetString("LabelPersonBirthDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЕГН.
        /// </summary>
        public static string LabelPersonEGN {
            get {
                return ResourceManager.GetString("LabelPersonEGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име.
        /// </summary>
        public static string LabelPersonFirstName {
            get {
                return ResourceManager.GetString("LabelPersonFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string LabelPersonLastName {
            get {
                return ResourceManager.GetString("LabelPersonLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Презиме.
        /// </summary>
        public static string LabelPersonMiddleName {
            get {
                return ResourceManager.GetString("LabelPersonMiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За промяна на име, презиме, фамилия чрез извличане на данни от ГРАО (за потребители с ЕГН), моля натиснете бутона &quot;Синхронизация на имена&quot;!.
        /// </summary>
        public static string LabelPersonUpdateNames {
            get {
                return ResourceManager.GetString("LabelPersonUpdateNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        public static string LabelPhone {
            get {
                return ResourceManager.GetString("LabelPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добави физическо лице, имащо достъп до профила.
        /// </summary>
        public static string LinkGrantAccess {
            get {
                return ResourceManager.GetString("LinkGrantAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повече.
        /// </summary>
        public static string LinkSignatureDataMore {
            get {
                return ResourceManager.GetString("LinkSignatureDataMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данни от подпис. Отвори линка.
        /// </summary>
        public static string LinkSignatureEgnInfo {
            get {
                return ResourceManager.GetString("LinkSignatureEgnInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сигурни ли сте, че желаете да изтриете превода?.
        /// </summary>
        public static string MessageConfirmDeleteTranslation {
            get {
                return ResourceManager.GetString("MessageConfirmDeleteTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сигурни ли сте, че желаете да премахнете достъпа до профила на {0}?.
        /// </summary>
        public static string MessageConfirmRemoveAccessForLogin {
            get {
                return ResourceManager.GetString("MessageConfirmRemoveAccessForLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вашите настройки бяха успешно обновени..
        /// </summary>
        public static string MessageSaveSettingsSuccess {
            get {
                return ResourceManager.GetString("MessageSaveSettingsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Промяната на данни наименование, ЕИК и представителство се извършват само след одобряване от администратор на системата!.
        /// </summary>
        public static string MessageUpdateInstitutionSpecific {
            get {
                return ResourceManager.GetString("MessageUpdateInstitutionSpecific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Промяната на данните име, данъчен номер и дата на влизане в сила се извършват само след одобряване от администратор на системата!.
        /// </summary>
        public static string MessageUpdateLegalSpecific {
            get {
                return ResourceManager.GetString("MessageUpdateLegalSpecific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Промяната на данните име, презиме, фамилия, ЕГН и дата на раждане се извършват само след одобряване от администратор на системата!.
        /// </summary>
        public static string MessageUpdatePersonSpecific {
            get {
                return ResourceManager.GetString("MessageUpdatePersonSpecific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Съобщение.
        /// </summary>
        public static string MessageWithCodeMessageSection {
            get {
                return ResourceManager.GetString("MessageWithCodeMessageSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получател.
        /// </summary>
        public static string MessageWithCodeReceiverSection {
            get {
                return ResourceManager.GetString("MessageWithCodeReceiverSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to От дата.
        /// </summary>
        public static string PlaceholderDateFrom {
            get {
                return ResourceManager.GetString("PlaceholderDateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to До дата.
        /// </summary>
        public static string PlaceholderDateТо {
            get {
                return ResourceManager.GetString("PlaceholderDateТо", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущо състояние.
        /// </summary>
        public static string PlaceholderStatus {
            get {
                return ResourceManager.GetString("PlaceholderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Смяна на профила.
        /// </summary>
        public static string ProfileChange {
            get {
                return ResourceManager.GetString("ProfileChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Няма прикачени документи към профила.
        /// </summary>
        public static string SectionAttachedDocumentsEmpty {
            get {
                return ResourceManager.GetString("SectionAttachedDocumentsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подписан от.
        /// </summary>
        public static string SignatureInformation {
            get {
                return ResourceManager.GetString("SignatureInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отваряне.
        /// </summary>
        public static string TableActionOpenMessage {
            get {
                return ResourceManager.GetString("TableActionOpenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Преглед.
        /// </summary>
        public static string TableActionViewMessage {
            get {
                return ResourceManager.GetString("TableActionViewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавен от.
        /// </summary>
        public static string TableGrantAccessHeaderGivenBy {
            get {
                return ResourceManager.GetString("TableGrantAccessHeaderGivenBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавен на.
        /// </summary>
        public static string TableGrantAccessHeaderGivenOn {
            get {
                return ResourceManager.GetString("TableGrantAccessHeaderGivenOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име.
        /// </summary>
        public static string TableGrantAccessHeaderName {
            get {
                return ResourceManager.GetString("TableGrantAccessHeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Връчено.
        /// </summary>
        public static string TableHeaderMessageDateReceived {
            get {
                return ResourceManager.GetString("TableHeaderMessageDateReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изпратено.
        /// </summary>
        public static string TableHeaderMessageDateSent {
            get {
                return ResourceManager.GetString("TableHeaderMessageDateSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получено от.
        /// </summary>
        public static string TableHeaderMessageReceivedBy {
            get {
                return ResourceManager.GetString("TableHeaderMessageReceivedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получател.
        /// </summary>
        public static string TableHeaderMessageReceiver {
            get {
                return ResourceManager.GetString("TableHeaderMessageReceiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Връчител.
        /// </summary>
        public static string TableHeaderMessageSender {
            get {
                return ResourceManager.GetString("TableHeaderMessageSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изпратено от.
        /// </summary>
        public static string TableHeaderMessageSentBy {
            get {
                return ResourceManager.GetString("TableHeaderMessageSentBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        public static string TableHeaderMessageStatus {
            get {
                return ResourceManager.GetString("TableHeaderMessageStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заглавие.
        /// </summary>
        public static string TableHeaderMessageTitle {
            get {
                return ResourceManager.GetString("TableHeaderMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Документ.
        /// </summary>
        public static string TableHeaderSubjectDocument {
            get {
                return ResourceManager.GetString("TableHeaderSubjectDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавен от.
        /// </summary>
        public static string TableHeaderSubjectDocumentAddedBy {
            get {
                return ResourceManager.GetString("TableHeaderSubjectDocumentAddedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавен на.
        /// </summary>
        public static string TableHeaderSubjectDocumentAddedOn {
            get {
                return ResourceManager.GetString("TableHeaderSubjectDocumentAddedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успешно валидиран подпис.
        /// </summary>
        public static string TextSigatureValidationValid {
            get {
                return ResourceManager.GetString("TextSigatureValidationValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подписът към документа има проблеми.
        /// </summary>
        public static string TextSignatureValidationWithErroс {
            get {
                return ResourceManager.GetString("TextSignatureValidationWithErroс", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to е променено на .
        /// </summary>
        public static string TextUpdatedTo {
            get {
                return ResourceManager.GetString("TextUpdatedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данни за административен орган.
        /// </summary>
        public static string TitleDataInstitution {
            get {
                return ResourceManager.GetString("TitleDataInstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данни за юридическо лице.
        /// </summary>
        public static string TitleDataLegal {
            get {
                return ResourceManager.GetString("TitleDataLegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данни за физическо лице.
        /// </summary>
        public static string TitleDataPerson {
            get {
                return ResourceManager.GetString("TitleDataPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данни от подпис към документ {0}.
        /// </summary>
        public static string TitleEgnInfo {
            get {
                return ResourceManager.GetString("TitleEgnInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детайли за препращането.
        /// </summary>
        public static string TitleForwardedMessageHistory {
            get {
                return ResourceManager.GetString("TitleForwardedMessageHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Достъп до профила.
        /// </summary>
        public static string TitleGrantAccessToProfile {
            get {
                return ResourceManager.GetString("TitleGrantAccessToProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Достъп до профила.
        /// </summary>
        public static string TitleProfileAccess {
            get {
                return ResourceManager.GetString("TitleProfileAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Търсене в изпратени съобщения.
        /// </summary>
        public static string TitleSearchInSentMessages {
            get {
                return ResourceManager.GetString("TitleSearchInSentMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Търсене в получени съобщения.
        /// </summary>
        public static string TitleSearchReceivedMessages {
            get {
                return ResourceManager.GetString("TitleSearchReceivedMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прикачени документи към профила.
        /// </summary>
        public static string TitleSectionAttachedDocuments {
            get {
                return ResourceManager.GetString("TitleSectionAttachedDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки на нотификациите.
        /// </summary>
        public static string TitleSectionNotificationSettings {
            get {
                return ResourceManager.GetString("TitleSectionNotificationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нотификации по e-mail.
        /// </summary>
        public static string TitleSectionNotificationSettingsViaEmail {
            get {
                return ResourceManager.GetString("TitleSectionNotificationSettingsViaEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нотификации по Viber/SMS.
        /// </summary>
        public static string TitleSectionNotificationSettingsViaPhone {
            get {
                return ResourceManager.GetString("TitleSectionNotificationSettingsViaPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Смяна на паролата.
        /// </summary>
        public static string TitleSectionPasswordChange {
            get {
                return ResourceManager.GetString("TitleSectionPasswordChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Валидация на подпис към документ {0}.
        /// </summary>
        public static string TitleSignatureInfo {
            get {
                return ResourceManager.GetString("TitleSignatureInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавяне на орган на ДА.
        /// </summary>
        public static string TooltipAddInstitution {
            get {
                return ResourceManager.GetString("TooltipAddInstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавяне на получател.
        /// </summary>
        public static string TooltipAddPersonOrLegal {
            get {
                return ResourceManager.GetString("TooltipAddPersonOrLegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удостоверение за време на изпращане.
        /// </summary>
        public static string TooltipDocumentTimestamp {
            get {
                return ResourceManager.GetString("TooltipDocumentTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изтегли документа.
        /// </summary>
        public static string TooltipDownloadDocument {
            get {
                return ResourceManager.GetString("TooltipDownloadDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свали  удостоверение за време на връчване.
        /// </summary>
        public static string TooltipDownloadNRD {
            get {
                return ResourceManager.GetString("TooltipDownloadNRD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свали  удостоверение за време на изпращане.
        /// </summary>
        public static string TooltipDownloadNRO {
            get {
                return ResourceManager.GetString("TooltipDownloadNRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удостоверение за електронно връчване.
        /// </summary>
        public static string TooltipDownloadStampPdfMessage {
            get {
                return ResourceManager.GetString("TooltipDownloadStampPdfMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свали съобщението в xml..
        /// </summary>
        public static string TooltipDownloadTimestampedMessage {
            get {
                return ResourceManager.GetString("TooltipDownloadTimestampedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Препратено.
        /// </summary>
        public static string TooltipMessageForwarded {
            get {
                return ResourceManager.GetString("TooltipMessageForwarded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ново.
        /// </summary>
        public static string TooltipMessageNew {
            get {
                return ResourceManager.GetString("TooltipMessageNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не е връчено.
        /// </summary>
        public static string TooltipMessageNotReceived {
            get {
                return ResourceManager.GetString("TooltipMessageNotReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отворено.
        /// </summary>
        public static string TooltipMessageOpened {
            get {
                return ResourceManager.GetString("TooltipMessageOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оригинално.
        /// </summary>
        public static string TooltipMessageOriginal {
            get {
                return ResourceManager.GetString("TooltipMessageOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Връчено.
        /// </summary>
        public static string TooltipMessageReceived {
            get {
                return ResourceManager.GetString("TooltipMessageReceived", resourceCulture);
            }
        }
    }
}
