//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDeliveryResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SEOS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SEOS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EDeliveryResources.SEOS", typeof(SEOS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действие.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да, свали документа.
        /// </summary>
        public static string AllowDownload {
            get {
                return ResourceManager.GetString("AllowDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добави още.
        /// </summary>
        public static string ButtonAddMoreDos {
            get {
                return ResourceManager.GetString("ButtonAddMoreDos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Провери статуса.
        /// </summary>
        public static string ButtonCheckStatus {
            get {
                return ResourceManager.GetString("ButtonCheckStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изпрати съобщение.
        /// </summary>
        public static string ButtonNewSEOSDocument {
            get {
                return ResourceManager.GetString("ButtonNewSEOSDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изпрати.
        /// </summary>
        public static string ButtonSendMessage {
            get {
                return ResourceManager.GetString("ButtonSendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Промени.
        /// </summary>
        public static string ButtonUpdateStatus {
            get {
                return ResourceManager.GetString("ButtonUpdateStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отказ.
        /// </summary>
        public static string DeclineDownload {
            get {
                return ResourceManager.GetString("DeclineDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изтегли документа.
        /// </summary>
        public static string DownloadAttachment {
            get {
                return ResourceManager.GetString("DownloadAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активен.
        /// </summary>
        public static string EntityStatusActive {
            get {
                return ResourceManager.GetString("EntityStatusActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не е активен.
        /// </summary>
        public static string EntityStatusInactive {
            get {
                return ResourceManager.GetString("EntityStatusInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Временно не е активен.
        /// </summary>
        public static string EntityStatusTemporaryInactive {
            get {
                return ResourceManager.GetString("EntityStatusTemporaryInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Липса на достъп! Документът не е проверен за наличие на зловреден код!.
        /// </summary>
        public static string ErrorCantAccessMalwareService {
            get {
                return ResourceManager.GetString("ErrorCantAccessMalwareService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файлът не може да бъде качен на сървъра! Моля, опитайте по-късно..
        /// </summary>
        public static string ErrorCantUploadFile {
            get {
                return ResourceManager.GetString("ErrorCantUploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проблем с достъпа до услугата!.
        /// </summary>
        public static string ErrorConnectingSEOSService {
            get {
                return ResourceManager.GetString("ErrorConnectingSEOSService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля, прикачете поне един документ!.
        /// </summary>
        public static string ErrorDocumenntRequired {
            get {
                return ResourceManager.GetString("ErrorDocumenntRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максималнияt брой символи в полето е {0}!.
        /// </summary>
        public static string ErrorExceededMaxLen {
            get {
                return ResourceManager.GetString("ErrorExceededMaxLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открит е зловреден код! Документът не може да бъде изпратен!.
        /// </summary>
        public static string ErrorMaliciousFile {
            get {
                return ResourceManager.GetString("ErrorMaliciousFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размерът на документа превишава лимита от 10MB!.
        /// </summary>
        public static string ErrorMaxFileLength {
            get {
                return ResourceManager.GetString("ErrorMaxFileLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Грешка! Документ {0} не е намерен!.
        /// </summary>
        public static string ErrorNotFoundAttachment {
            get {
                return ResourceManager.GetString("ErrorNotFoundAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Грешка! Съобщение с идентификатор {0} не е намерено!.
        /// </summary>
        public static string ErrorNotFoundMessage {
            get {
                return ResourceManager.GetString("ErrorNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Липсва отговор от антивирусна компонента! Документът не е проверен за наличие на зловреден код!.
        /// </summary>
        public static string ErrorPendingScanResult {
            get {
                return ResourceManager.GetString("ErrorPendingScanResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля, изберете документ за прикачване!.
        /// </summary>
        public static string ErrorPleaseSelectFile {
            get {
                return ResourceManager.GetString("ErrorPleaseSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открит е зловреден код!.
        /// </summary>
        public static string ErrorReceivedDocumentIsMalicious {
            get {
                return ResourceManager.GetString("ErrorReceivedDocumentIsMalicious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Документът не е проверен за наличие на зловреден код! Желаете ли да го свалите на свой риск и отговорност?.
        /// </summary>
        public static string ErrorReceivedDocumentIsNotCheckedForMalware {
            get {
                return ResourceManager.GetString("ErrorReceivedDocumentIsNotCheckedForMalware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето е задължително!.
        /// </summary>
        public static string ErrorRejectReasonMissing {
            get {
                return ResourceManager.GetString("ErrorRejectReasonMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето е задължително!.
        /// </summary>
        public static string ErrorRequired {
            get {
                return ResourceManager.GetString("ErrorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Възникна грешка при изпращане на документа! Моля опитайте по-късно!.
        /// </summary>
        public static string ErrorSubmitNewDocument {
            get {
                return ResourceManager.GetString("ErrorSubmitNewDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Грешка! Опит за неоторизиран достъп до файл  {0}.
        /// </summary>
        public static string ErrorUnauthorizedAccesssToAttachment {
            get {
                return ResourceManager.GetString("ErrorUnauthorizedAccesssToAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Грешка! Опит за неоторизиран достъп до съобщение с идентификатор {0}.
        /// </summary>
        public static string ErrorUnauthorizedAccesssToMessage {
            get {
                return ResourceManager.GetString("ErrorUnauthorizedAccesssToMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Грешка! Документът не е проверен за наличие на зловреден код! Това не пречи документа да бъде изпратен непроверен!.
        /// </summary>
        public static string ErrorUnsuccessfulScan {
            get {
                return ResourceManager.GetString("ErrorUnsuccessfulScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Възникна грешка при актуализиране на статуса! Моля, опитайте по-късно..
        /// </summary>
        public static string ErrorUpdatingStatus {
            get {
                return ResourceManager.GetString("ErrorUpdatingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Документът е успешно проверен и не са открити вируси!.
        /// </summary>
        public static string InfoFileIsNotMalicious {
            get {
                return ResourceManager.GetString("InfoFileIsNotMalicious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Можете да изпратите съобщение като изберете получател от регистъра на СЕОС и натиснете бутон &quot;Изпрати съобщение&quot; на съответния ред.
        /// </summary>
        public static string InfoMessageChooseEntityToSendDocument {
            get {
                return ResourceManager.GetString("InfoMessageChooseEntityToSendDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рег. индекс (изпращач).
        /// </summary>
        public static string LabeExternalRegIndex1 {
            get {
                return ResourceManager.GetString("LabeExternalRegIndex1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Допълнителни данни.
        /// </summary>
        public static string LabelAdditionalData {
            get {
                return ResourceManager.GetString("LabelAdditionalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име.
        /// </summary>
        public static string LabelCorespondent {
            get {
                return ResourceManager.GetString("LabelCorespondent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес.
        /// </summary>
        public static string LabelCorespondentAddress {
            get {
                return ResourceManager.GetString("LabelCorespondentAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Булстат.
        /// </summary>
        public static string LabelCorespondentBulstat {
            get {
                return ResourceManager.GetString("LabelCorespondentBulstat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тел./E-mail.
        /// </summary>
        public static string LabelCorespondentContact {
            get {
                return ResourceManager.GetString("LabelCorespondentContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЕГН.
        /// </summary>
        public static string LabelCorespondentEGN {
            get {
                return ResourceManager.GetString("LabelCorespondentEGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Но. личен документ.
        /// </summary>
        public static string LabelCorespondentIDCard {
            get {
                return ResourceManager.GetString("LabelCorespondentIDCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЕГН/ЛНЧ.
        /// </summary>
        public static string LabelCorespondentIdentifier {
            get {
                return ResourceManager.GetString("LabelCorespondentIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to МОЛ.
        /// </summary>
        public static string LabelCorespondentMOL {
            get {
                return ResourceManager.GetString("LabelCorespondentMOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кореспонденти.
        /// </summary>
        public static string LabelCorespondents {
            get {
                return ResourceManager.GetString("LabelCorespondents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получено на.
        /// </summary>
        public static string LabelDateReceived {
            get {
                return ResourceManager.GetString("LabelDateReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрирано на.
        /// </summary>
        public static string LabelDateRegistered {
            get {
                return ResourceManager.GetString("LabelDateRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изпратено на.
        /// </summary>
        public static string LabelDateSent {
            get {
                return ResourceManager.GetString("LabelDateSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата на статуса.
        /// </summary>
        public static string LabelDateStatusUpdate {
            get {
                return ResourceManager.GetString("LabelDateStatusUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Допълнителен коментар.
        /// </summary>
        public static string LabelDocAdditionalComment {
            get {
                return ResourceManager.GetString("LabelDocAdditionalComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На вниманието на.
        /// </summary>
        public static string LabelDocAttentionTo {
            get {
                return ResourceManager.GetString("LabelDocAttentionTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прикачени файлове.
        /// </summary>
        public static string LabelDocAttList {
            get {
                return ResourceManager.GetString("LabelDocAttList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уникален идентификатор.
        /// </summary>
        public static string LabelDocId {
            get {
                return ResourceManager.GetString("LabelDocId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид.
        /// </summary>
        public static string LabelDocKind {
            get {
                return ResourceManager.GetString("LabelDocKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рег. индекс в АИС на изпращача.
        /// </summary>
        public static string LabelDocReferenceNumber {
            get {
                return ResourceManager.GetString("LabelDocReferenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Краен срок за приключване.
        /// </summary>
        public static string LabelDocRequestEndDate {
            get {
                return ResourceManager.GetString("LabelDocRequestEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коментар към документа.
        /// </summary>
        public static string LabelDocumentAttComment {
            get {
                return ResourceManager.GetString("LabelDocumentAttComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прикачен файл.
        /// </summary>
        public static string LabelDocumentAttName {
            get {
                return ResourceManager.GetString("LabelDocumentAttName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Път до документа.
        /// </summary>
        public static string LabelDocumentAttPath {
            get {
                return ResourceManager.GetString("LabelDocumentAttPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изтегляне.
        /// </summary>
        public static string LabelDownloadDocument {
            get {
                return ResourceManager.GetString("LabelDownloadDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очаквана дата за приключване на работата.
        /// </summary>
        public static string LabelExpectedDateClose {
            get {
                return ResourceManager.GetString("LabelExpectedDateClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рег. индекс (получател).
        /// </summary>
        public static string LabelExternalRegIndex {
            get {
                return ResourceManager.GetString("LabelExternalRegIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рег. индекс (е-Връчване).
        /// </summary>
        public static string LabelInternalRegIndex {
            get {
                return ResourceManager.GetString("LabelInternalRegIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        public static string LabelNewStatus {
            get {
                return ResourceManager.GetString("LabelNewStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Родителски документ.
        /// </summary>
        public static string LabelParentDocName {
            get {
                return ResourceManager.GetString("LabelParentDocName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получател.
        /// </summary>
        public static string LabelReceiverName {
            get {
                return ResourceManager.GetString("LabelReceiverName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрирано от.
        /// </summary>
        public static string LabelRegisteredByLoginName {
            get {
                return ResourceManager.GetString("LabelRegisteredByLoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основание.
        /// </summary>
        public static string LabelRejectedReason {
            get {
                return ResourceManager.GetString("LabelRejectedReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Причина за отказ от регистрация.
        /// </summary>
        public static string LabelRejectReason {
            get {
                return ResourceManager.GetString("LabelRejectReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kраен срок за приключване.
        /// </summary>
        public static string LabelReqEndDate {
            get {
                return ResourceManager.GetString("LabelReqEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изпращач.
        /// </summary>
        public static string LabelSenderName {
            get {
                return ResourceManager.GetString("LabelSenderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изпратено от.
        /// </summary>
        public static string LabelSentByLoginNames {
            get {
                return ResourceManager.GetString("LabelSentByLoginNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адм. услуга.
        /// </summary>
        public static string LabelService {
            get {
                return ResourceManager.GetString("LabelService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код на услугата.
        /// </summary>
        public static string LabelServiceCode {
            get {
                return ResourceManager.GetString("LabelServiceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код / Тип на адм. услуга.
        /// </summary>
        public static string LabelServiceCodeAndType {
            get {
                return ResourceManager.GetString("LabelServiceCodeAndType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип на услугата.
        /// </summary>
        public static string LabelServiceType {
            get {
                return ResourceManager.GetString("LabelServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        public static string LabelStatus {
            get {
                return ResourceManager.GetString("LabelStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Относно.
        /// </summary>
        public static string LabelSubject {
            get {
                return ResourceManager.GetString("LabelSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Промяна на статуса.
        /// </summary>
        public static string LabelUpdateStatus {
            get {
                return ResourceManager.GetString("LabelUpdateStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Съобщение.
        /// </summary>
        public static string MessageAction {
            get {
                return ResourceManager.GetString("MessageAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не са намерени участници в СЕОС.
        /// </summary>
        public static string MessageNoEntities {
            get {
                return ResourceManager.GetString("MessageNoEntities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не са намерени участничи в СЕОС, отговарящи на зададения критерий за търсене!.
        /// </summary>
        public static string MessageNoEntitiesForSearch {
            get {
                return ResourceManager.GetString("MessageNoEntitiesForSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Няма получени съобщения през СЕОС.
        /// </summary>
        public static string MessageNoReceivedDocuments {
            get {
                return ResourceManager.GetString("MessageNoReceivedDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Няма изпратени съобщения през СЕОС.
        /// </summary>
        public static string MessageNoSentDocuments {
            get {
                return ResourceManager.GetString("MessageNoSentDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отваряне.
        /// </summary>
        public static string OpenDocument {
            get {
                return ResourceManager.GetString("OpenDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Преглед на получен документ.
        /// </summary>
        public static string OpenReceivedDocument {
            get {
                return ResourceManager.GetString("OpenReceivedDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Преглед на изпратен документ.
        /// </summary>
        public static string OpenSentDocument {
            get {
                return ResourceManager.GetString("OpenSentDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профилът на {0} няма регистрация като участник в Система за електронен обмен на съобщения (СЕОС). За да бъде използвана функционалността СЕОС през системата за електронно връчване, необходимо е да се направи съответна регистрация в регистъра на участниците в СЕОС.
        ///&lt;br/&gt;
        ///За повече информация и лица за контакт, посетете &lt;a href=&quot;https://e-gov.bg/bg/119&quot; target=&quot;_blank&quot;&gt;https://e-gov.bg/bg/119&lt;/a&gt;
        ///&lt;br/&gt;
        ///&lt;h3&gt;
        ///&lt;strong&gt;Внимание! &lt;/strong&gt;&lt;/h3&gt;
        ///&lt;br/&gt;
        ///Ако вашата документооборотна система е включена към СЕОС, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ProfileNoSEOSMessage {
            get {
                return ResourceManager.GetString("ProfileNoSEOSMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получени съобщения през СЕОС.
        /// </summary>
        public static string ReceivedDocumentsTitle {
            get {
                return ResourceManager.GetString("ReceivedDocumentsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Участници в СЕОС.
        /// </summary>
        public static string RegisteredEntities {
            get {
                return ResourceManager.GetString("RegisteredEntities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Търси.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Част от име или ЕИК.
        /// </summary>
        public static string SearchEntity {
            get {
                return ResourceManager.GetString("SearchEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изпрати документ на участник в СЕОС.
        /// </summary>
        public static string SendDocumentToEntity {
            get {
                return ResourceManager.GetString("SendDocumentToEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изпратени съобщения през СЕОС.
        /// </summary>
        public static string SentDocumentsTitle {
            get {
                return ResourceManager.GetString("SentDocumentsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получено.
        /// </summary>
        public static string StatusAlreadyReceived {
            get {
                return ResourceManager.GetString("StatusAlreadyReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приключено.
        /// </summary>
        public static string StatusClosed {
            get {
                return ResourceManager.GetString("StatusClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не е открито.
        /// </summary>
        public static string StatusNotFound {
            get {
                return ResourceManager.GetString("StatusNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрирано.
        /// </summary>
        public static string StatusRegistered {
            get {
                return ResourceManager.GetString("StatusRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отказано.
        /// </summary>
        public static string StatusRejected {
            get {
                return ResourceManager.GetString("StatusRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В процес на изпращане.
        /// </summary>
        public static string StatusSending {
            get {
                return ResourceManager.GetString("StatusSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изпратено.
        /// </summary>
        public static string StatusSent {
            get {
                return ResourceManager.GetString("StatusSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неуспешно изпращане.
        /// </summary>
        public static string StatusSentFailed {
            get {
                return ResourceManager.GetString("StatusSentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спряно.
        /// </summary>
        public static string StatusStopped {
            get {
                return ResourceManager.GetString("StatusStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очаква регистрация.
        /// </summary>
        public static string StatusWaitRegistration {
            get {
                return ResourceManager.GetString("StatusWaitRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Преглед на съобщението.
        /// </summary>
        public static string TableActionOpenMessage {
            get {
                return ResourceManager.GetString("TableActionOpenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получено на.
        /// </summary>
        public static string TableHeaderDateReceived {
            get {
                return ResourceManager.GetString("TableHeaderDateReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изпратено на.
        /// </summary>
        public static string TableHeaderDateSent {
            get {
                return ResourceManager.GetString("TableHeaderDateSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Относно.
        /// </summary>
        public static string TableHeaderDocAbout {
            get {
                return ResourceManager.GetString("TableHeaderDocAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид на документа.
        /// </summary>
        public static string TableHeaderDocKind {
            get {
                return ResourceManager.GetString("TableHeaderDocKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        public static string TableHeaderDocStatus {
            get {
                return ResourceManager.GetString("TableHeaderDocStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рег. индекс.
        /// </summary>
        public static string TableHeadeRegIndex {
            get {
                return ResourceManager.GetString("TableHeadeRegIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЕИК.
        /// </summary>
        public static string TableHeaderEIK {
            get {
                return ResourceManager.GetString("TableHeaderEIK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string TableHeaderEmail {
            get {
                return ResourceManager.GetString("TableHeaderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЕИК.
        /// </summary>
        public static string TableHeaderEntityEIK {
            get {
                return ResourceManager.GetString("TableHeaderEntityEIK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Организация.
        /// </summary>
        public static string TableHeaderEntityName {
            get {
                return ResourceManager.GetString("TableHeaderEntityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        public static string TableHeaderEntityStatus {
            get {
                return ResourceManager.GetString("TableHeaderEntityStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        public static string TableHeaderPhone {
            get {
                return ResourceManager.GetString("TableHeaderPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получател.
        /// </summary>
        public static string TableHeaderReceiver {
            get {
                return ResourceManager.GetString("TableHeaderReceiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получено от.
        /// </summary>
        public static string TableHeaderSender {
            get {
                return ResourceManager.GetString("TableHeaderSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to УРЛ на услугата.
        /// </summary>
        public static string TableHeaderServiceURL {
            get {
                return ResourceManager.GetString("TableHeaderServiceURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Създаване на ново съобщение за електронен обмен.
        /// </summary>
        public static string TitleCreateNewSEOSMessage {
            get {
                return ResourceManager.GetString("TitleCreateNewSEOSMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помощ за работа със СЕОС.
        /// </summary>
        public static string TitleHelp {
            get {
                return ResourceManager.GetString("TitleHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Система за електронен обмен на съобщения (СЕОС).
        /// </summary>
        public static string TitleSEOS {
            get {
                return ResourceManager.GetString("TitleSEOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предупреждение.
        /// </summary>
        public static string WarningTitle {
            get {
                return ResourceManager.GetString("WarningTitle", resourceCulture);
            }
        }
    }
}
