//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDeliveryResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EDeliveryResources.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недокументиран отговор на заявка от услугата за превод.
        /// </summary>
        public static string _2 {
            get {
                return ResourceManager.GetString("2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Липсва език на оригиналния текст.
        /// </summary>
        public static string _20000 {
            get {
                return ResourceManager.GetString("20000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невалиден език на оригиналния текст.
        /// </summary>
        public static string _20001 {
            get {
                return ResourceManager.GetString("20001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Липсва целеви език.
        /// </summary>
        public static string _20002 {
            get {
                return ResourceManager.GetString("20002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невалиден целеви език.
        /// </summary>
        public static string _20003 {
            get {
                return ResourceManager.GetString("20003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Надвишаване на квотата за превод.
        /// </summary>
        public static string _20028 {
            get {
                return ResourceManager.GetString("20028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неподдържан формат на документа.
        /// </summary>
        public static string _20029 {
            get {
                return ResourceManager.GetString("20029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Липсва текст/документ за превод.
        /// </summary>
        public static string _20031 {
            get {
                return ResourceManager.GetString("20031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Документът е прекалено голям за превод.
        /// </summary>
        public static string _20046 {
            get {
                return ResourceManager.GetString("20046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прекалено много сегменти за превод.
        /// </summary>
        public static string _40010 {
            get {
                return ResourceManager.GetString("40010", resourceCulture);
            }
        }
    }
}
