//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDeliveryResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIControls {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIControls() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EDeliveryResources.UIControls", typeof(UIControls).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прикачи.
        /// </summary>
        public static string ButtonAttach {
            get {
                return ResourceManager.GetString("ButtonAttach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        public static string ButtonBack {
            get {
                return ResourceManager.GetString("ButtonBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отказ.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВХОД.
        /// </summary>
        public static string ButtonLogin {
            get {
                return ResourceManager.GetString("ButtonLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изход.
        /// </summary>
        public static string ButtonLogout {
            get {
                return ResourceManager.GetString("ButtonLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОК.
        /// </summary>
        public static string ButtonOk {
            get {
                return ResourceManager.GetString("ButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to РЕГИСТРАЦИЯ.
        /// </summary>
        public static string ButtonRegister {
            get {
                return ResourceManager.GetString("ButtonRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запис.
        /// </summary>
        public static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Търси.
        /// </summary>
        public static string ButtonSearch {
            get {
                return ResourceManager.GetString("ButtonSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изпрати.
        /// </summary>
        public static string ButtonSend {
            get {
                return ResourceManager.GetString("ButtonSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изпрати заявка за автентикация.
        /// </summary>
        public static string ButtonSendRequest {
            get {
                return ResourceManager.GetString("ButtonSendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Система за еВалидиране.
        /// </summary>
        public static string LinkEValidation {
            get {
                return ResourceManager.GetString("LinkEValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помощна информация.
        /// </summary>
        public static string LinkHelpInfo {
            get {
                return ResourceManager.GetString("LinkHelpInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Научете повече.
        /// </summary>
        public static string LinkLearnMode {
            get {
                return ResourceManager.GetString("LinkLearnMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адм. орган.
        /// </summary>
        public static string MainMavInstitution {
            get {
                return ResourceManager.GetString("MainMavInstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Административни органи.
        /// </summary>
        public static string MainMavInstitutions {
            get {
                return ResourceManager.GetString("MainMavInstitutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Юридическо лице.
        /// </summary>
        public static string MainMavLegalPerson {
            get {
                return ResourceManager.GetString("MainMavLegalPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Други ЮЛ.
        /// </summary>
        public static string MainMavLegalPersons {
            get {
                return ResourceManager.GetString("MainMavLegalPersons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Физическо лице.
        /// </summary>
        public static string MainNavPhysicalPerson {
            get {
                return ResourceManager.GetString("MainNavPhysicalPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лица по чл.1, ал.2 ЗЕУ.
        /// </summary>
        public static string MainNavSocialOrganisation {
            get {
                return ResourceManager.GetString("MainNavSocialOrganisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лица по чл. 1, ал 2 ЗЕУ.
        /// </summary>
        public static string MainNavSocialOrganisations {
            get {
                return ResourceManager.GetString("MainNavSocialOrganisations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Има {0} нови съобщения!.
        /// </summary>
        public static string NewEDeliveryMessagesTooltip {
            get {
                return ResourceManager.GetString("NewEDeliveryMessagesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Има {0} нови СЕОС документа!.
        /// </summary>
        public static string NewSEOSMessagesTooltip {
            get {
                return ResourceManager.GetString("NewSEOSMessagesTooltip", resourceCulture);
            }
        }
    }
}
